// Code generated by ent, DO NOT EDIT.

package baiduvodvideotask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the baiduvodvideotask type in the database.
	Label = "baidu_vod_video_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldUpstreamRequestID holds the string denoting the upstream_request_id field in the database.
	FieldUpstreamRequestID = "upstream_request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldCapability holds the string denoting the capability field in the database.
	FieldCapability = "capability"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldRatio holds the string denoting the ratio field in the database.
	FieldRatio = "ratio"
	// FieldRequestedDuration holds the string denoting the requested_duration field in the database.
	FieldRequestedDuration = "requested_duration"
	// FieldOutputDuration holds the string denoting the output_duration field in the database.
	FieldOutputDuration = "output_duration"
	// FieldInputVideoDuration holds the string denoting the input_video_duration field in the database.
	FieldInputVideoDuration = "input_video_duration"
	// FieldVideoCount holds the string denoting the video_count field in the database.
	FieldVideoCount = "video_count"
	// FieldEstimatedCost holds the string denoting the estimated_cost field in the database.
	FieldEstimatedCost = "estimated_cost"
	// FieldHoldAmount holds the string denoting the hold_amount field in the database.
	FieldHoldAmount = "hold_amount"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldGroupRateMultiplier holds the string denoting the group_rate_multiplier field in the database.
	FieldGroupRateMultiplier = "group_rate_multiplier"
	// FieldVideoRateMultiplier holds the string denoting the video_rate_multiplier field in the database.
	FieldVideoRateMultiplier = "video_rate_multiplier"
	// FieldAccountRateMultiplier holds the string denoting the account_rate_multiplier field in the database.
	FieldAccountRateMultiplier = "account_rate_multiplier"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldResultURL holds the string denoting the result_url field in the database.
	FieldResultURL = "result_url"
	// FieldResultExpiresAt holds the string denoting the result_expires_at field in the database.
	FieldResultExpiresAt = "result_expires_at"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldNextPollAt holds the string denoting the next_poll_at field in the database.
	FieldNextPollAt = "next_poll_at"
	// FieldPollClaimedUntil holds the string denoting the poll_claimed_until field in the database.
	FieldPollClaimedUntil = "poll_claimed_until"
	// FieldLastPolledAt holds the string denoting the last_polled_at field in the database.
	FieldLastPolledAt = "last_polled_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// Table holds the table name of the baiduvodvideotask in the database.
	Table = "baidu_vod_video_tasks"
)

// Columns holds all SQL columns for baiduvodvideotask fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldProvider,
	FieldTaskID,
	FieldUpstreamTaskID,
	FieldUpstreamRequestID,
	FieldUserID,
	FieldAPIKeyID,
	FieldAccountID,
	FieldGroupID,
	FieldModel,
	FieldUpstreamModel,
	FieldCapability,
	FieldStatus,
	FieldUpstreamStatus,
	FieldResolution,
	FieldRatio,
	FieldRequestedDuration,
	FieldOutputDuration,
	FieldInputVideoDuration,
	FieldVideoCount,
	FieldEstimatedCost,
	FieldHoldAmount,
	FieldActualCost,
	FieldGroupRateMultiplier,
	FieldVideoRateMultiplier,
	FieldAccountRateMultiplier,
	FieldRequestHash,
	FieldResultURL,
	FieldResultExpiresAt,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldRetryCount,
	FieldVersion,
	FieldNextPollAt,
	FieldPollClaimedUntil,
	FieldLastPolledAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSubmittedAt,
	FieldStartedAt,
	FieldFinishedAt,
	FieldSettledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	TaskIDValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// UpstreamRequestIDValidator is a validator for the "upstream_request_id" field. It is called by the builders before save.
	UpstreamRequestIDValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// CapabilityValidator is a validator for the "capability" field. It is called by the builders before save.
	CapabilityValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultUpstreamStatus holds the default value on creation for the "upstream_status" field.
	DefaultUpstreamStatus string
	// UpstreamStatusValidator is a validator for the "upstream_status" field. It is called by the builders before save.
	UpstreamStatusValidator func(string) error
	// ResolutionValidator is a validator for the "resolution" field. It is called by the builders before save.
	ResolutionValidator func(string) error
	// DefaultRatio holds the default value on creation for the "ratio" field.
	DefaultRatio string
	// RatioValidator is a validator for the "ratio" field. It is called by the builders before save.
	RatioValidator func(string) error
	// DefaultOutputDuration holds the default value on creation for the "output_duration" field.
	DefaultOutputDuration int
	// DefaultInputVideoDuration holds the default value on creation for the "input_video_duration" field.
	DefaultInputVideoDuration int
	// DefaultVideoCount holds the default value on creation for the "video_count" field.
	DefaultVideoCount int
	// DefaultEstimatedCost holds the default value on creation for the "estimated_cost" field.
	DefaultEstimatedCost float64
	// DefaultHoldAmount holds the default value on creation for the "hold_amount" field.
	DefaultHoldAmount float64
	// DefaultGroupRateMultiplier holds the default value on creation for the "group_rate_multiplier" field.
	DefaultGroupRateMultiplier float64
	// DefaultVideoRateMultiplier holds the default value on creation for the "video_rate_multiplier" field.
	DefaultVideoRateMultiplier float64
	// DefaultAccountRateMultiplier holds the default value on creation for the "account_rate_multiplier" field.
	DefaultAccountRateMultiplier float64
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// LastErrorCodeValidator is a validator for the "last_error_code" field. It is called by the builders before save.
	LastErrorCodeValidator func(string) error
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// DefaultNextPollAt holds the default value on creation for the "next_poll_at" field.
	DefaultNextPollAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSubmittedAt holds the default value on creation for the "submitted_at" field.
	DefaultSubmittedAt func() time.Time
)

// OrderOption defines the ordering options for the BaiduVODVideoTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByUpstreamRequestID orders the results by the upstream_request_id field.
func ByUpstreamRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByCapability orders the results by the capability field.
func ByCapability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapability, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}

// ByRatio orders the results by the ratio field.
func ByRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatio, opts...).ToFunc()
}

// ByRequestedDuration orders the results by the requested_duration field.
func ByRequestedDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedDuration, opts...).ToFunc()
}

// ByOutputDuration orders the results by the output_duration field.
func ByOutputDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputDuration, opts...).ToFunc()
}

// ByInputVideoDuration orders the results by the input_video_duration field.
func ByInputVideoDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputVideoDuration, opts...).ToFunc()
}

// ByVideoCount orders the results by the video_count field.
func ByVideoCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoCount, opts...).ToFunc()
}

// ByEstimatedCost orders the results by the estimated_cost field.
func ByEstimatedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedCost, opts...).ToFunc()
}

// ByHoldAmount orders the results by the hold_amount field.
func ByHoldAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldAmount, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByGroupRateMultiplier orders the results by the group_rate_multiplier field.
func ByGroupRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupRateMultiplier, opts...).ToFunc()
}

// ByVideoRateMultiplier orders the results by the video_rate_multiplier field.
func ByVideoRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoRateMultiplier, opts...).ToFunc()
}

// ByAccountRateMultiplier orders the results by the account_rate_multiplier field.
func ByAccountRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountRateMultiplier, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByResultURL orders the results by the result_url field.
func ByResultURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultURL, opts...).ToFunc()
}

// ByResultExpiresAt orders the results by the result_expires_at field.
func ByResultExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultExpiresAt, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByNextPollAt orders the results by the next_poll_at field.
func ByNextPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextPollAt, opts...).ToFunc()
}

// ByPollClaimedUntil orders the results by the poll_claimed_until field.
func ByPollClaimedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollClaimedUntil, opts...).ToFunc()
}

// ByLastPolledAt orders the results by the last_polled_at field.
func ByLastPolledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPolledAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}
