// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/baiduvodvideotask"
)

// BaiduVODVideoTaskCreate is the builder for creating a BaiduVODVideoTask entity.
type BaiduVODVideoTaskCreate struct {
	config
	mutation *BaiduVODVideoTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlatform sets the "platform" field.
func (_c *BaiduVODVideoTaskCreate) SetPlatform(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillablePlatform(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *BaiduVODVideoTaskCreate) SetProvider(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableProvider(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *BaiduVODVideoTaskCreate) SetTaskID(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *BaiduVODVideoTaskCreate) SetUpstreamTaskID(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_c *BaiduVODVideoTaskCreate) SetUpstreamRequestID(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetUpstreamRequestID(v)
	return _c
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableUpstreamRequestID(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetUpstreamRequestID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BaiduVODVideoTaskCreate) SetUserID(v int64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *BaiduVODVideoTaskCreate) SetAPIKeyID(v int64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *BaiduVODVideoTaskCreate) SetAccountID(v int64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *BaiduVODVideoTaskCreate) SetGroupID(v int64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableGroupID(v *int64) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *BaiduVODVideoTaskCreate) SetModel(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *BaiduVODVideoTaskCreate) SetUpstreamModel(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetCapability sets the "capability" field.
func (_c *BaiduVODVideoTaskCreate) SetCapability(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetCapability(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *BaiduVODVideoTaskCreate) SetStatus(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableStatus(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_c *BaiduVODVideoTaskCreate) SetUpstreamStatus(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetUpstreamStatus(v)
	return _c
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableUpstreamStatus(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetUpstreamStatus(*v)
	}
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *BaiduVODVideoTaskCreate) SetResolution(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetRatio sets the "ratio" field.
func (_c *BaiduVODVideoTaskCreate) SetRatio(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetRatio(v)
	return _c
}

// SetNillableRatio sets the "ratio" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableRatio(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetRatio(*v)
	}
	return _c
}

// SetRequestedDuration sets the "requested_duration" field.
func (_c *BaiduVODVideoTaskCreate) SetRequestedDuration(v int) *BaiduVODVideoTaskCreate {
	_c.mutation.SetRequestedDuration(v)
	return _c
}

// SetOutputDuration sets the "output_duration" field.
func (_c *BaiduVODVideoTaskCreate) SetOutputDuration(v int) *BaiduVODVideoTaskCreate {
	_c.mutation.SetOutputDuration(v)
	return _c
}

// SetNillableOutputDuration sets the "output_duration" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableOutputDuration(v *int) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetOutputDuration(*v)
	}
	return _c
}

// SetInputVideoDuration sets the "input_video_duration" field.
func (_c *BaiduVODVideoTaskCreate) SetInputVideoDuration(v int) *BaiduVODVideoTaskCreate {
	_c.mutation.SetInputVideoDuration(v)
	return _c
}

// SetNillableInputVideoDuration sets the "input_video_duration" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableInputVideoDuration(v *int) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetInputVideoDuration(*v)
	}
	return _c
}

// SetVideoCount sets the "video_count" field.
func (_c *BaiduVODVideoTaskCreate) SetVideoCount(v int) *BaiduVODVideoTaskCreate {
	_c.mutation.SetVideoCount(v)
	return _c
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableVideoCount(v *int) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetVideoCount(*v)
	}
	return _c
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_c *BaiduVODVideoTaskCreate) SetEstimatedCost(v float64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetEstimatedCost(v)
	return _c
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableEstimatedCost(v *float64) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetEstimatedCost(*v)
	}
	return _c
}

// SetHoldAmount sets the "hold_amount" field.
func (_c *BaiduVODVideoTaskCreate) SetHoldAmount(v float64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetHoldAmount(v)
	return _c
}

// SetNillableHoldAmount sets the "hold_amount" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableHoldAmount(v *float64) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetHoldAmount(*v)
	}
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *BaiduVODVideoTaskCreate) SetActualCost(v float64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableActualCost(v *float64) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetActualCost(*v)
	}
	return _c
}

// SetGroupRateMultiplier sets the "group_rate_multiplier" field.
func (_c *BaiduVODVideoTaskCreate) SetGroupRateMultiplier(v float64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetGroupRateMultiplier(v)
	return _c
}

// SetNillableGroupRateMultiplier sets the "group_rate_multiplier" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableGroupRateMultiplier(v *float64) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetGroupRateMultiplier(*v)
	}
	return _c
}

// SetVideoRateMultiplier sets the "video_rate_multiplier" field.
func (_c *BaiduVODVideoTaskCreate) SetVideoRateMultiplier(v float64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetVideoRateMultiplier(v)
	return _c
}

// SetNillableVideoRateMultiplier sets the "video_rate_multiplier" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableVideoRateMultiplier(v *float64) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetVideoRateMultiplier(*v)
	}
	return _c
}

// SetAccountRateMultiplier sets the "account_rate_multiplier" field.
func (_c *BaiduVODVideoTaskCreate) SetAccountRateMultiplier(v float64) *BaiduVODVideoTaskCreate {
	_c.mutation.SetAccountRateMultiplier(v)
	return _c
}

// SetNillableAccountRateMultiplier sets the "account_rate_multiplier" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableAccountRateMultiplier(v *float64) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetAccountRateMultiplier(*v)
	}
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *BaiduVODVideoTaskCreate) SetRequestHash(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetResultURL sets the "result_url" field.
func (_c *BaiduVODVideoTaskCreate) SetResultURL(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetResultURL(v)
	return _c
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableResultURL(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetResultURL(*v)
	}
	return _c
}

// SetResultExpiresAt sets the "result_expires_at" field.
func (_c *BaiduVODVideoTaskCreate) SetResultExpiresAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetResultExpiresAt(v)
	return _c
}

// SetNillableResultExpiresAt sets the "result_expires_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableResultExpiresAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetResultExpiresAt(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *BaiduVODVideoTaskCreate) SetLastErrorCode(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableLastErrorCode(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_c *BaiduVODVideoTaskCreate) SetLastErrorMessage(v string) *BaiduVODVideoTaskCreate {
	_c.mutation.SetLastErrorMessage(v)
	return _c
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableLastErrorMessage(v *string) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetLastErrorMessage(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *BaiduVODVideoTaskCreate) SetRetryCount(v int) *BaiduVODVideoTaskCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableRetryCount(v *int) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *BaiduVODVideoTaskCreate) SetVersion(v int) *BaiduVODVideoTaskCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableVersion(v *int) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetNextPollAt sets the "next_poll_at" field.
func (_c *BaiduVODVideoTaskCreate) SetNextPollAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetNextPollAt(v)
	return _c
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableNextPollAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetNextPollAt(*v)
	}
	return _c
}

// SetPollClaimedUntil sets the "poll_claimed_until" field.
func (_c *BaiduVODVideoTaskCreate) SetPollClaimedUntil(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetPollClaimedUntil(v)
	return _c
}

// SetNillablePollClaimedUntil sets the "poll_claimed_until" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillablePollClaimedUntil(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetPollClaimedUntil(*v)
	}
	return _c
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_c *BaiduVODVideoTaskCreate) SetLastPolledAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetLastPolledAt(v)
	return _c
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableLastPolledAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetLastPolledAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BaiduVODVideoTaskCreate) SetCreatedAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableCreatedAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BaiduVODVideoTaskCreate) SetUpdatedAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableUpdatedAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *BaiduVODVideoTaskCreate) SetSubmittedAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableSubmittedAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *BaiduVODVideoTaskCreate) SetStartedAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableStartedAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *BaiduVODVideoTaskCreate) SetFinishedAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableFinishedAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetSettledAt sets the "settled_at" field.
func (_c *BaiduVODVideoTaskCreate) SetSettledAt(v time.Time) *BaiduVODVideoTaskCreate {
	_c.mutation.SetSettledAt(v)
	return _c
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_c *BaiduVODVideoTaskCreate) SetNillableSettledAt(v *time.Time) *BaiduVODVideoTaskCreate {
	if v != nil {
		_c.SetSettledAt(*v)
	}
	return _c
}

// Mutation returns the BaiduVODVideoTaskMutation object of the builder.
func (_c *BaiduVODVideoTaskCreate) Mutation() *BaiduVODVideoTaskMutation {
	return _c.mutation
}

// Save creates the BaiduVODVideoTask in the database.
func (_c *BaiduVODVideoTaskCreate) Save(ctx context.Context) (*BaiduVODVideoTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BaiduVODVideoTaskCreate) SaveX(ctx context.Context) *BaiduVODVideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BaiduVODVideoTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BaiduVODVideoTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BaiduVODVideoTaskCreate) defaults() {
	if _, ok := _c.mutation.Platform(); !ok {
		v := baiduvodvideotask.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := baiduvodvideotask.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := baiduvodvideotask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UpstreamStatus(); !ok {
		v := baiduvodvideotask.DefaultUpstreamStatus
		_c.mutation.SetUpstreamStatus(v)
	}
	if _, ok := _c.mutation.Ratio(); !ok {
		v := baiduvodvideotask.DefaultRatio
		_c.mutation.SetRatio(v)
	}
	if _, ok := _c.mutation.OutputDuration(); !ok {
		v := baiduvodvideotask.DefaultOutputDuration
		_c.mutation.SetOutputDuration(v)
	}
	if _, ok := _c.mutation.InputVideoDuration(); !ok {
		v := baiduvodvideotask.DefaultInputVideoDuration
		_c.mutation.SetInputVideoDuration(v)
	}
	if _, ok := _c.mutation.VideoCount(); !ok {
		v := baiduvodvideotask.DefaultVideoCount
		_c.mutation.SetVideoCount(v)
	}
	if _, ok := _c.mutation.EstimatedCost(); !ok {
		v := baiduvodvideotask.DefaultEstimatedCost
		_c.mutation.SetEstimatedCost(v)
	}
	if _, ok := _c.mutation.HoldAmount(); !ok {
		v := baiduvodvideotask.DefaultHoldAmount
		_c.mutation.SetHoldAmount(v)
	}
	if _, ok := _c.mutation.GroupRateMultiplier(); !ok {
		v := baiduvodvideotask.DefaultGroupRateMultiplier
		_c.mutation.SetGroupRateMultiplier(v)
	}
	if _, ok := _c.mutation.VideoRateMultiplier(); !ok {
		v := baiduvodvideotask.DefaultVideoRateMultiplier
		_c.mutation.SetVideoRateMultiplier(v)
	}
	if _, ok := _c.mutation.AccountRateMultiplier(); !ok {
		v := baiduvodvideotask.DefaultAccountRateMultiplier
		_c.mutation.SetAccountRateMultiplier(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := baiduvodvideotask.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := baiduvodvideotask.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.NextPollAt(); !ok {
		v := baiduvodvideotask.DefaultNextPollAt()
		_c.mutation.SetNextPollAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := baiduvodvideotask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := baiduvodvideotask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		v := baiduvodvideotask.DefaultSubmittedAt()
		_c.mutation.SetSubmittedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BaiduVODVideoTaskCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "BaiduVODVideoTask.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := baiduvodvideotask.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "BaiduVODVideoTask.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := baiduvodvideotask.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "BaiduVODVideoTask.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := baiduvodvideotask.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamTaskID(); !ok {
		return &ValidationError{Name: "upstream_task_id", err: errors.New(`ent: missing required field "BaiduVODVideoTask.upstream_task_id"`)}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := baiduvodvideotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamRequestID(); ok {
		if err := baiduvodvideotask.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BaiduVODVideoTask.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "BaiduVODVideoTask.api_key_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "BaiduVODVideoTask.account_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "BaiduVODVideoTask.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := baiduvodvideotask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "BaiduVODVideoTask.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := baiduvodvideotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Capability(); !ok {
		return &ValidationError{Name: "capability", err: errors.New(`ent: missing required field "BaiduVODVideoTask.capability"`)}
	}
	if v, ok := _c.mutation.Capability(); ok {
		if err := baiduvodvideotask.CapabilityValidator(v); err != nil {
			return &ValidationError{Name: "capability", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.capability": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BaiduVODVideoTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := baiduvodvideotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamStatus(); !ok {
		return &ValidationError{Name: "upstream_status", err: errors.New(`ent: missing required field "BaiduVODVideoTask.upstream_status"`)}
	}
	if v, ok := _c.mutation.UpstreamStatus(); ok {
		if err := baiduvodvideotask.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Resolution(); !ok {
		return &ValidationError{Name: "resolution", err: errors.New(`ent: missing required field "BaiduVODVideoTask.resolution"`)}
	}
	if v, ok := _c.mutation.Resolution(); ok {
		if err := baiduvodvideotask.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.resolution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ratio(); !ok {
		return &ValidationError{Name: "ratio", err: errors.New(`ent: missing required field "BaiduVODVideoTask.ratio"`)}
	}
	if v, ok := _c.mutation.Ratio(); ok {
		if err := baiduvodvideotask.RatioValidator(v); err != nil {
			return &ValidationError{Name: "ratio", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.ratio": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedDuration(); !ok {
		return &ValidationError{Name: "requested_duration", err: errors.New(`ent: missing required field "BaiduVODVideoTask.requested_duration"`)}
	}
	if _, ok := _c.mutation.OutputDuration(); !ok {
		return &ValidationError{Name: "output_duration", err: errors.New(`ent: missing required field "BaiduVODVideoTask.output_duration"`)}
	}
	if _, ok := _c.mutation.InputVideoDuration(); !ok {
		return &ValidationError{Name: "input_video_duration", err: errors.New(`ent: missing required field "BaiduVODVideoTask.input_video_duration"`)}
	}
	if _, ok := _c.mutation.VideoCount(); !ok {
		return &ValidationError{Name: "video_count", err: errors.New(`ent: missing required field "BaiduVODVideoTask.video_count"`)}
	}
	if _, ok := _c.mutation.EstimatedCost(); !ok {
		return &ValidationError{Name: "estimated_cost", err: errors.New(`ent: missing required field "BaiduVODVideoTask.estimated_cost"`)}
	}
	if _, ok := _c.mutation.HoldAmount(); !ok {
		return &ValidationError{Name: "hold_amount", err: errors.New(`ent: missing required field "BaiduVODVideoTask.hold_amount"`)}
	}
	if _, ok := _c.mutation.GroupRateMultiplier(); !ok {
		return &ValidationError{Name: "group_rate_multiplier", err: errors.New(`ent: missing required field "BaiduVODVideoTask.group_rate_multiplier"`)}
	}
	if _, ok := _c.mutation.VideoRateMultiplier(); !ok {
		return &ValidationError{Name: "video_rate_multiplier", err: errors.New(`ent: missing required field "BaiduVODVideoTask.video_rate_multiplier"`)}
	}
	if _, ok := _c.mutation.AccountRateMultiplier(); !ok {
		return &ValidationError{Name: "account_rate_multiplier", err: errors.New(`ent: missing required field "BaiduVODVideoTask.account_rate_multiplier"`)}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "BaiduVODVideoTask.request_hash"`)}
	}
	if v, ok := _c.mutation.RequestHash(); ok {
		if err := baiduvodvideotask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastErrorCode(); ok {
		if err := baiduvodvideotask.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.last_error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "BaiduVODVideoTask.retry_count"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "BaiduVODVideoTask.version"`)}
	}
	if _, ok := _c.mutation.NextPollAt(); !ok {
		return &ValidationError{Name: "next_poll_at", err: errors.New(`ent: missing required field "BaiduVODVideoTask.next_poll_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BaiduVODVideoTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BaiduVODVideoTask.updated_at"`)}
	}
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		return &ValidationError{Name: "submitted_at", err: errors.New(`ent: missing required field "BaiduVODVideoTask.submitted_at"`)}
	}
	return nil
}

func (_c *BaiduVODVideoTaskCreate) sqlSave(ctx context.Context) (*BaiduVODVideoTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BaiduVODVideoTaskCreate) createSpec() (*BaiduVODVideoTask, *sqlgraph.CreateSpec) {
	var (
		_node = &BaiduVODVideoTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(baiduvodvideotask.Table, sqlgraph.NewFieldSpec(baiduvodvideotask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(baiduvodvideotask.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(baiduvodvideotask.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(baiduvodvideotask.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = value
	}
	if value, ok := _c.mutation.UpstreamRequestID(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamRequestID, field.TypeString, value)
		_node.UpstreamRequestID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(baiduvodvideotask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(baiduvodvideotask.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(baiduvodvideotask.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(baiduvodvideotask.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(baiduvodvideotask.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.Capability(); ok {
		_spec.SetField(baiduvodvideotask.FieldCapability, field.TypeString, value)
		_node.Capability = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(baiduvodvideotask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UpstreamStatus(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamStatus, field.TypeString, value)
		_node.UpstreamStatus = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(baiduvodvideotask.FieldResolution, field.TypeString, value)
		_node.Resolution = value
	}
	if value, ok := _c.mutation.Ratio(); ok {
		_spec.SetField(baiduvodvideotask.FieldRatio, field.TypeString, value)
		_node.Ratio = value
	}
	if value, ok := _c.mutation.RequestedDuration(); ok {
		_spec.SetField(baiduvodvideotask.FieldRequestedDuration, field.TypeInt, value)
		_node.RequestedDuration = value
	}
	if value, ok := _c.mutation.OutputDuration(); ok {
		_spec.SetField(baiduvodvideotask.FieldOutputDuration, field.TypeInt, value)
		_node.OutputDuration = value
	}
	if value, ok := _c.mutation.InputVideoDuration(); ok {
		_spec.SetField(baiduvodvideotask.FieldInputVideoDuration, field.TypeInt, value)
		_node.InputVideoDuration = value
	}
	if value, ok := _c.mutation.VideoCount(); ok {
		_spec.SetField(baiduvodvideotask.FieldVideoCount, field.TypeInt, value)
		_node.VideoCount = value
	}
	if value, ok := _c.mutation.EstimatedCost(); ok {
		_spec.SetField(baiduvodvideotask.FieldEstimatedCost, field.TypeFloat64, value)
		_node.EstimatedCost = value
	}
	if value, ok := _c.mutation.HoldAmount(); ok {
		_spec.SetField(baiduvodvideotask.FieldHoldAmount, field.TypeFloat64, value)
		_node.HoldAmount = value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(baiduvodvideotask.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = &value
	}
	if value, ok := _c.mutation.GroupRateMultiplier(); ok {
		_spec.SetField(baiduvodvideotask.FieldGroupRateMultiplier, field.TypeFloat64, value)
		_node.GroupRateMultiplier = value
	}
	if value, ok := _c.mutation.VideoRateMultiplier(); ok {
		_spec.SetField(baiduvodvideotask.FieldVideoRateMultiplier, field.TypeFloat64, value)
		_node.VideoRateMultiplier = value
	}
	if value, ok := _c.mutation.AccountRateMultiplier(); ok {
		_spec.SetField(baiduvodvideotask.FieldAccountRateMultiplier, field.TypeFloat64, value)
		_node.AccountRateMultiplier = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(baiduvodvideotask.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.ResultURL(); ok {
		_spec.SetField(baiduvodvideotask.FieldResultURL, field.TypeString, value)
		_node.ResultURL = &value
	}
	if value, ok := _c.mutation.ResultExpiresAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldResultExpiresAt, field.TypeTime, value)
		_node.ResultExpiresAt = &value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = &value
	}
	if value, ok := _c.mutation.LastErrorMessage(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastErrorMessage, field.TypeString, value)
		_node.LastErrorMessage = &value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(baiduvodvideotask.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(baiduvodvideotask.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.NextPollAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldNextPollAt, field.TypeTime, value)
		_node.NextPollAt = value
	}
	if value, ok := _c.mutation.PollClaimedUntil(); ok {
		_spec.SetField(baiduvodvideotask.FieldPollClaimedUntil, field.TypeTime, value)
		_node.PollClaimedUntil = &value
	}
	if value, ok := _c.mutation.LastPolledAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastPolledAt, field.TypeTime, value)
		_node.LastPolledAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.SettledAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldSettledAt, field.TypeTime, value)
		_node.SettledAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BaiduVODVideoTask.Create().
//		SetPlatform(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BaiduVODVideoTaskUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *BaiduVODVideoTaskCreate) OnConflict(opts ...sql.ConflictOption) *BaiduVODVideoTaskUpsertOne {
	_c.conflict = opts
	return &BaiduVODVideoTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BaiduVODVideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BaiduVODVideoTaskCreate) OnConflictColumns(columns ...string) *BaiduVODVideoTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BaiduVODVideoTaskUpsertOne{
		create: _c,
	}
}

type (
	// BaiduVODVideoTaskUpsertOne is the builder for "upsert"-ing
	//  one BaiduVODVideoTask node.
	BaiduVODVideoTaskUpsertOne struct {
		create *BaiduVODVideoTaskCreate
	}

	// BaiduVODVideoTaskUpsert is the "OnConflict" setter.
	BaiduVODVideoTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *BaiduVODVideoTaskUpsert) SetUpstreamRequestID(v string) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldUpstreamRequestID, v)
	return u
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateUpstreamRequestID() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldUpstreamRequestID)
	return u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *BaiduVODVideoTaskUpsert) ClearUpstreamRequestID() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldUpstreamRequestID)
	return u
}

// SetStatus sets the "status" field.
func (u *BaiduVODVideoTaskUpsert) SetStatus(v string) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateStatus() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldStatus)
	return u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *BaiduVODVideoTaskUpsert) SetUpstreamStatus(v string) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldUpstreamStatus, v)
	return u
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateUpstreamStatus() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldUpstreamStatus)
	return u
}

// SetOutputDuration sets the "output_duration" field.
func (u *BaiduVODVideoTaskUpsert) SetOutputDuration(v int) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldOutputDuration, v)
	return u
}

// UpdateOutputDuration sets the "output_duration" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateOutputDuration() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldOutputDuration)
	return u
}

// AddOutputDuration adds v to the "output_duration" field.
func (u *BaiduVODVideoTaskUpsert) AddOutputDuration(v int) *BaiduVODVideoTaskUpsert {
	u.Add(baiduvodvideotask.FieldOutputDuration, v)
	return u
}

// SetInputVideoDuration sets the "input_video_duration" field.
func (u *BaiduVODVideoTaskUpsert) SetInputVideoDuration(v int) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldInputVideoDuration, v)
	return u
}

// UpdateInputVideoDuration sets the "input_video_duration" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateInputVideoDuration() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldInputVideoDuration)
	return u
}

// AddInputVideoDuration adds v to the "input_video_duration" field.
func (u *BaiduVODVideoTaskUpsert) AddInputVideoDuration(v int) *BaiduVODVideoTaskUpsert {
	u.Add(baiduvodvideotask.FieldInputVideoDuration, v)
	return u
}

// SetVideoCount sets the "video_count" field.
func (u *BaiduVODVideoTaskUpsert) SetVideoCount(v int) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldVideoCount, v)
	return u
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateVideoCount() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldVideoCount)
	return u
}

// AddVideoCount adds v to the "video_count" field.
func (u *BaiduVODVideoTaskUpsert) AddVideoCount(v int) *BaiduVODVideoTaskUpsert {
	u.Add(baiduvodvideotask.FieldVideoCount, v)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsert) SetActualCost(v float64) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateActualCost() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsert) AddActualCost(v float64) *BaiduVODVideoTaskUpsert {
	u.Add(baiduvodvideotask.FieldActualCost, v)
	return u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsert) ClearActualCost() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldActualCost)
	return u
}

// SetResultURL sets the "result_url" field.
func (u *BaiduVODVideoTaskUpsert) SetResultURL(v string) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldResultURL, v)
	return u
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateResultURL() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldResultURL)
	return u
}

// ClearResultURL clears the value of the "result_url" field.
func (u *BaiduVODVideoTaskUpsert) ClearResultURL() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldResultURL)
	return u
}

// SetResultExpiresAt sets the "result_expires_at" field.
func (u *BaiduVODVideoTaskUpsert) SetResultExpiresAt(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldResultExpiresAt, v)
	return u
}

// UpdateResultExpiresAt sets the "result_expires_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateResultExpiresAt() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldResultExpiresAt)
	return u
}

// ClearResultExpiresAt clears the value of the "result_expires_at" field.
func (u *BaiduVODVideoTaskUpsert) ClearResultExpiresAt() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldResultExpiresAt)
	return u
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *BaiduVODVideoTaskUpsert) SetLastErrorCode(v string) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldLastErrorCode, v)
	return u
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateLastErrorCode() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldLastErrorCode)
	return u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *BaiduVODVideoTaskUpsert) ClearLastErrorCode() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldLastErrorCode)
	return u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *BaiduVODVideoTaskUpsert) SetLastErrorMessage(v string) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldLastErrorMessage, v)
	return u
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateLastErrorMessage() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldLastErrorMessage)
	return u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (u *BaiduVODVideoTaskUpsert) ClearLastErrorMessage() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldLastErrorMessage)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *BaiduVODVideoTaskUpsert) SetRetryCount(v int) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateRetryCount() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *BaiduVODVideoTaskUpsert) AddRetryCount(v int) *BaiduVODVideoTaskUpsert {
	u.Add(baiduvodvideotask.FieldRetryCount, v)
	return u
}

// SetVersion sets the "version" field.
func (u *BaiduVODVideoTaskUpsert) SetVersion(v int) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateVersion() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *BaiduVODVideoTaskUpsert) AddVersion(v int) *BaiduVODVideoTaskUpsert {
	u.Add(baiduvodvideotask.FieldVersion, v)
	return u
}

// SetNextPollAt sets the "next_poll_at" field.
func (u *BaiduVODVideoTaskUpsert) SetNextPollAt(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldNextPollAt, v)
	return u
}

// UpdateNextPollAt sets the "next_poll_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateNextPollAt() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldNextPollAt)
	return u
}

// SetPollClaimedUntil sets the "poll_claimed_until" field.
func (u *BaiduVODVideoTaskUpsert) SetPollClaimedUntil(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldPollClaimedUntil, v)
	return u
}

// UpdatePollClaimedUntil sets the "poll_claimed_until" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdatePollClaimedUntil() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldPollClaimedUntil)
	return u
}

// ClearPollClaimedUntil clears the value of the "poll_claimed_until" field.
func (u *BaiduVODVideoTaskUpsert) ClearPollClaimedUntil() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldPollClaimedUntil)
	return u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *BaiduVODVideoTaskUpsert) SetLastPolledAt(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldLastPolledAt, v)
	return u
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateLastPolledAt() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldLastPolledAt)
	return u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *BaiduVODVideoTaskUpsert) ClearLastPolledAt() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldLastPolledAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BaiduVODVideoTaskUpsert) SetUpdatedAt(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateUpdatedAt() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldUpdatedAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *BaiduVODVideoTaskUpsert) SetStartedAt(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateStartedAt() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *BaiduVODVideoTaskUpsert) ClearStartedAt() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *BaiduVODVideoTaskUpsert) SetFinishedAt(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateFinishedAt() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *BaiduVODVideoTaskUpsert) ClearFinishedAt() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldFinishedAt)
	return u
}

// SetSettledAt sets the "settled_at" field.
func (u *BaiduVODVideoTaskUpsert) SetSettledAt(v time.Time) *BaiduVODVideoTaskUpsert {
	u.Set(baiduvodvideotask.FieldSettledAt, v)
	return u
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsert) UpdateSettledAt() *BaiduVODVideoTaskUpsert {
	u.SetExcluded(baiduvodvideotask.FieldSettledAt)
	return u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *BaiduVODVideoTaskUpsert) ClearSettledAt() *BaiduVODVideoTaskUpsert {
	u.SetNull(baiduvodvideotask.FieldSettledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BaiduVODVideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BaiduVODVideoTaskUpsertOne) UpdateNewValues() *BaiduVODVideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Platform(); exists {
			s.SetIgnore(baiduvodvideotask.FieldPlatform)
		}
		if _, exists := u.create.mutation.Provider(); exists {
			s.SetIgnore(baiduvodvideotask.FieldProvider)
		}
		if _, exists := u.create.mutation.TaskID(); exists {
			s.SetIgnore(baiduvodvideotask.FieldTaskID)
		}
		if _, exists := u.create.mutation.UpstreamTaskID(); exists {
			s.SetIgnore(baiduvodvideotask.FieldUpstreamTaskID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(baiduvodvideotask.FieldUserID)
		}
		if _, exists := u.create.mutation.APIKeyID(); exists {
			s.SetIgnore(baiduvodvideotask.FieldAPIKeyID)
		}
		if _, exists := u.create.mutation.AccountID(); exists {
			s.SetIgnore(baiduvodvideotask.FieldAccountID)
		}
		if _, exists := u.create.mutation.GroupID(); exists {
			s.SetIgnore(baiduvodvideotask.FieldGroupID)
		}
		if _, exists := u.create.mutation.Model(); exists {
			s.SetIgnore(baiduvodvideotask.FieldModel)
		}
		if _, exists := u.create.mutation.UpstreamModel(); exists {
			s.SetIgnore(baiduvodvideotask.FieldUpstreamModel)
		}
		if _, exists := u.create.mutation.Capability(); exists {
			s.SetIgnore(baiduvodvideotask.FieldCapability)
		}
		if _, exists := u.create.mutation.Resolution(); exists {
			s.SetIgnore(baiduvodvideotask.FieldResolution)
		}
		if _, exists := u.create.mutation.Ratio(); exists {
			s.SetIgnore(baiduvodvideotask.FieldRatio)
		}
		if _, exists := u.create.mutation.RequestedDuration(); exists {
			s.SetIgnore(baiduvodvideotask.FieldRequestedDuration)
		}
		if _, exists := u.create.mutation.EstimatedCost(); exists {
			s.SetIgnore(baiduvodvideotask.FieldEstimatedCost)
		}
		if _, exists := u.create.mutation.HoldAmount(); exists {
			s.SetIgnore(baiduvodvideotask.FieldHoldAmount)
		}
		if _, exists := u.create.mutation.GroupRateMultiplier(); exists {
			s.SetIgnore(baiduvodvideotask.FieldGroupRateMultiplier)
		}
		if _, exists := u.create.mutation.VideoRateMultiplier(); exists {
			s.SetIgnore(baiduvodvideotask.FieldVideoRateMultiplier)
		}
		if _, exists := u.create.mutation.AccountRateMultiplier(); exists {
			s.SetIgnore(baiduvodvideotask.FieldAccountRateMultiplier)
		}
		if _, exists := u.create.mutation.RequestHash(); exists {
			s.SetIgnore(baiduvodvideotask.FieldRequestHash)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(baiduvodvideotask.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.SubmittedAt(); exists {
			s.SetIgnore(baiduvodvideotask.FieldSubmittedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BaiduVODVideoTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BaiduVODVideoTaskUpsertOne) Ignore() *BaiduVODVideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BaiduVODVideoTaskUpsertOne) DoNothing() *BaiduVODVideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BaiduVODVideoTaskCreate.OnConflict
// documentation for more info.
func (u *BaiduVODVideoTaskUpsertOne) Update(set func(*BaiduVODVideoTaskUpsert)) *BaiduVODVideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BaiduVODVideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *BaiduVODVideoTaskUpsertOne) SetUpstreamRequestID(v string) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetUpstreamRequestID(v)
	})
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateUpstreamRequestID() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateUpstreamRequestID()
	})
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearUpstreamRequestID() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearUpstreamRequestID()
	})
}

// SetStatus sets the "status" field.
func (u *BaiduVODVideoTaskUpsertOne) SetStatus(v string) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateStatus() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *BaiduVODVideoTaskUpsertOne) SetUpstreamStatus(v string) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetUpstreamStatus(v)
	})
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateUpstreamStatus() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateUpstreamStatus()
	})
}

// SetOutputDuration sets the "output_duration" field.
func (u *BaiduVODVideoTaskUpsertOne) SetOutputDuration(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetOutputDuration(v)
	})
}

// AddOutputDuration adds v to the "output_duration" field.
func (u *BaiduVODVideoTaskUpsertOne) AddOutputDuration(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddOutputDuration(v)
	})
}

// UpdateOutputDuration sets the "output_duration" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateOutputDuration() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateOutputDuration()
	})
}

// SetInputVideoDuration sets the "input_video_duration" field.
func (u *BaiduVODVideoTaskUpsertOne) SetInputVideoDuration(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetInputVideoDuration(v)
	})
}

// AddInputVideoDuration adds v to the "input_video_duration" field.
func (u *BaiduVODVideoTaskUpsertOne) AddInputVideoDuration(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddInputVideoDuration(v)
	})
}

// UpdateInputVideoDuration sets the "input_video_duration" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateInputVideoDuration() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateInputVideoDuration()
	})
}

// SetVideoCount sets the "video_count" field.
func (u *BaiduVODVideoTaskUpsertOne) SetVideoCount(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetVideoCount(v)
	})
}

// AddVideoCount adds v to the "video_count" field.
func (u *BaiduVODVideoTaskUpsertOne) AddVideoCount(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddVideoCount(v)
	})
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateVideoCount() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateVideoCount()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsertOne) SetActualCost(v float64) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsertOne) AddActualCost(v float64) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateActualCost() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearActualCost() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearActualCost()
	})
}

// SetResultURL sets the "result_url" field.
func (u *BaiduVODVideoTaskUpsertOne) SetResultURL(v string) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetResultURL(v)
	})
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateResultURL() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateResultURL()
	})
}

// ClearResultURL clears the value of the "result_url" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearResultURL() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearResultURL()
	})
}

// SetResultExpiresAt sets the "result_expires_at" field.
func (u *BaiduVODVideoTaskUpsertOne) SetResultExpiresAt(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetResultExpiresAt(v)
	})
}

// UpdateResultExpiresAt sets the "result_expires_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateResultExpiresAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateResultExpiresAt()
	})
}

// ClearResultExpiresAt clears the value of the "result_expires_at" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearResultExpiresAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearResultExpiresAt()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *BaiduVODVideoTaskUpsertOne) SetLastErrorCode(v string) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateLastErrorCode() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearLastErrorCode() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *BaiduVODVideoTaskUpsertOne) SetLastErrorMessage(v string) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetLastErrorMessage(v)
	})
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateLastErrorMessage() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateLastErrorMessage()
	})
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearLastErrorMessage() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearLastErrorMessage()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *BaiduVODVideoTaskUpsertOne) SetRetryCount(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *BaiduVODVideoTaskUpsertOne) AddRetryCount(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateRetryCount() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateRetryCount()
	})
}

// SetVersion sets the "version" field.
func (u *BaiduVODVideoTaskUpsertOne) SetVersion(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *BaiduVODVideoTaskUpsertOne) AddVersion(v int) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateVersion() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateVersion()
	})
}

// SetNextPollAt sets the "next_poll_at" field.
func (u *BaiduVODVideoTaskUpsertOne) SetNextPollAt(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetNextPollAt(v)
	})
}

// UpdateNextPollAt sets the "next_poll_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateNextPollAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateNextPollAt()
	})
}

// SetPollClaimedUntil sets the "poll_claimed_until" field.
func (u *BaiduVODVideoTaskUpsertOne) SetPollClaimedUntil(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetPollClaimedUntil(v)
	})
}

// UpdatePollClaimedUntil sets the "poll_claimed_until" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdatePollClaimedUntil() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdatePollClaimedUntil()
	})
}

// ClearPollClaimedUntil clears the value of the "poll_claimed_until" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearPollClaimedUntil() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearPollClaimedUntil()
	})
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *BaiduVODVideoTaskUpsertOne) SetLastPolledAt(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetLastPolledAt(v)
	})
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateLastPolledAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateLastPolledAt()
	})
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearLastPolledAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearLastPolledAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BaiduVODVideoTaskUpsertOne) SetUpdatedAt(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateUpdatedAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *BaiduVODVideoTaskUpsertOne) SetStartedAt(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateStartedAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearStartedAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *BaiduVODVideoTaskUpsertOne) SetFinishedAt(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateFinishedAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearFinishedAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *BaiduVODVideoTaskUpsertOne) SetSettledAt(v time.Time) *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertOne) UpdateSettledAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *BaiduVODVideoTaskUpsertOne) ClearSettledAt() *BaiduVODVideoTaskUpsertOne {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearSettledAt()
	})
}

// Exec executes the query.
func (u *BaiduVODVideoTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BaiduVODVideoTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BaiduVODVideoTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BaiduVODVideoTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BaiduVODVideoTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BaiduVODVideoTaskCreateBulk is the builder for creating many BaiduVODVideoTask entities in bulk.
type BaiduVODVideoTaskCreateBulk struct {
	config
	err      error
	builders []*BaiduVODVideoTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the BaiduVODVideoTask entities in the database.
func (_c *BaiduVODVideoTaskCreateBulk) Save(ctx context.Context) ([]*BaiduVODVideoTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BaiduVODVideoTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BaiduVODVideoTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BaiduVODVideoTaskCreateBulk) SaveX(ctx context.Context) []*BaiduVODVideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BaiduVODVideoTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BaiduVODVideoTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BaiduVODVideoTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BaiduVODVideoTaskUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *BaiduVODVideoTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *BaiduVODVideoTaskUpsertBulk {
	_c.conflict = opts
	return &BaiduVODVideoTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BaiduVODVideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BaiduVODVideoTaskCreateBulk) OnConflictColumns(columns ...string) *BaiduVODVideoTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BaiduVODVideoTaskUpsertBulk{
		create: _c,
	}
}

// BaiduVODVideoTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of BaiduVODVideoTask nodes.
type BaiduVODVideoTaskUpsertBulk struct {
	create *BaiduVODVideoTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BaiduVODVideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BaiduVODVideoTaskUpsertBulk) UpdateNewValues() *BaiduVODVideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Platform(); exists {
				s.SetIgnore(baiduvodvideotask.FieldPlatform)
			}
			if _, exists := b.mutation.Provider(); exists {
				s.SetIgnore(baiduvodvideotask.FieldProvider)
			}
			if _, exists := b.mutation.TaskID(); exists {
				s.SetIgnore(baiduvodvideotask.FieldTaskID)
			}
			if _, exists := b.mutation.UpstreamTaskID(); exists {
				s.SetIgnore(baiduvodvideotask.FieldUpstreamTaskID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(baiduvodvideotask.FieldUserID)
			}
			if _, exists := b.mutation.APIKeyID(); exists {
				s.SetIgnore(baiduvodvideotask.FieldAPIKeyID)
			}
			if _, exists := b.mutation.AccountID(); exists {
				s.SetIgnore(baiduvodvideotask.FieldAccountID)
			}
			if _, exists := b.mutation.GroupID(); exists {
				s.SetIgnore(baiduvodvideotask.FieldGroupID)
			}
			if _, exists := b.mutation.Model(); exists {
				s.SetIgnore(baiduvodvideotask.FieldModel)
			}
			if _, exists := b.mutation.UpstreamModel(); exists {
				s.SetIgnore(baiduvodvideotask.FieldUpstreamModel)
			}
			if _, exists := b.mutation.Capability(); exists {
				s.SetIgnore(baiduvodvideotask.FieldCapability)
			}
			if _, exists := b.mutation.Resolution(); exists {
				s.SetIgnore(baiduvodvideotask.FieldResolution)
			}
			if _, exists := b.mutation.Ratio(); exists {
				s.SetIgnore(baiduvodvideotask.FieldRatio)
			}
			if _, exists := b.mutation.RequestedDuration(); exists {
				s.SetIgnore(baiduvodvideotask.FieldRequestedDuration)
			}
			if _, exists := b.mutation.EstimatedCost(); exists {
				s.SetIgnore(baiduvodvideotask.FieldEstimatedCost)
			}
			if _, exists := b.mutation.HoldAmount(); exists {
				s.SetIgnore(baiduvodvideotask.FieldHoldAmount)
			}
			if _, exists := b.mutation.GroupRateMultiplier(); exists {
				s.SetIgnore(baiduvodvideotask.FieldGroupRateMultiplier)
			}
			if _, exists := b.mutation.VideoRateMultiplier(); exists {
				s.SetIgnore(baiduvodvideotask.FieldVideoRateMultiplier)
			}
			if _, exists := b.mutation.AccountRateMultiplier(); exists {
				s.SetIgnore(baiduvodvideotask.FieldAccountRateMultiplier)
			}
			if _, exists := b.mutation.RequestHash(); exists {
				s.SetIgnore(baiduvodvideotask.FieldRequestHash)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(baiduvodvideotask.FieldCreatedAt)
			}
			if _, exists := b.mutation.SubmittedAt(); exists {
				s.SetIgnore(baiduvodvideotask.FieldSubmittedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BaiduVODVideoTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BaiduVODVideoTaskUpsertBulk) Ignore() *BaiduVODVideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BaiduVODVideoTaskUpsertBulk) DoNothing() *BaiduVODVideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BaiduVODVideoTaskCreateBulk.OnConflict
// documentation for more info.
func (u *BaiduVODVideoTaskUpsertBulk) Update(set func(*BaiduVODVideoTaskUpsert)) *BaiduVODVideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BaiduVODVideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetUpstreamRequestID(v string) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetUpstreamRequestID(v)
	})
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateUpstreamRequestID() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateUpstreamRequestID()
	})
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearUpstreamRequestID() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearUpstreamRequestID()
	})
}

// SetStatus sets the "status" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetStatus(v string) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateStatus() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetUpstreamStatus(v string) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetUpstreamStatus(v)
	})
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateUpstreamStatus() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateUpstreamStatus()
	})
}

// SetOutputDuration sets the "output_duration" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetOutputDuration(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetOutputDuration(v)
	})
}

// AddOutputDuration adds v to the "output_duration" field.
func (u *BaiduVODVideoTaskUpsertBulk) AddOutputDuration(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddOutputDuration(v)
	})
}

// UpdateOutputDuration sets the "output_duration" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateOutputDuration() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateOutputDuration()
	})
}

// SetInputVideoDuration sets the "input_video_duration" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetInputVideoDuration(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetInputVideoDuration(v)
	})
}

// AddInputVideoDuration adds v to the "input_video_duration" field.
func (u *BaiduVODVideoTaskUpsertBulk) AddInputVideoDuration(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddInputVideoDuration(v)
	})
}

// UpdateInputVideoDuration sets the "input_video_duration" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateInputVideoDuration() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateInputVideoDuration()
	})
}

// SetVideoCount sets the "video_count" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetVideoCount(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetVideoCount(v)
	})
}

// AddVideoCount adds v to the "video_count" field.
func (u *BaiduVODVideoTaskUpsertBulk) AddVideoCount(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddVideoCount(v)
	})
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateVideoCount() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateVideoCount()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetActualCost(v float64) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsertBulk) AddActualCost(v float64) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateActualCost() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearActualCost() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearActualCost()
	})
}

// SetResultURL sets the "result_url" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetResultURL(v string) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetResultURL(v)
	})
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateResultURL() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateResultURL()
	})
}

// ClearResultURL clears the value of the "result_url" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearResultURL() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearResultURL()
	})
}

// SetResultExpiresAt sets the "result_expires_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetResultExpiresAt(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetResultExpiresAt(v)
	})
}

// UpdateResultExpiresAt sets the "result_expires_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateResultExpiresAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateResultExpiresAt()
	})
}

// ClearResultExpiresAt clears the value of the "result_expires_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearResultExpiresAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearResultExpiresAt()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetLastErrorCode(v string) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateLastErrorCode() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearLastErrorCode() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetLastErrorMessage(v string) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetLastErrorMessage(v)
	})
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateLastErrorMessage() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateLastErrorMessage()
	})
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearLastErrorMessage() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearLastErrorMessage()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetRetryCount(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *BaiduVODVideoTaskUpsertBulk) AddRetryCount(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateRetryCount() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateRetryCount()
	})
}

// SetVersion sets the "version" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetVersion(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *BaiduVODVideoTaskUpsertBulk) AddVersion(v int) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateVersion() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateVersion()
	})
}

// SetNextPollAt sets the "next_poll_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetNextPollAt(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetNextPollAt(v)
	})
}

// UpdateNextPollAt sets the "next_poll_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateNextPollAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateNextPollAt()
	})
}

// SetPollClaimedUntil sets the "poll_claimed_until" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetPollClaimedUntil(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetPollClaimedUntil(v)
	})
}

// UpdatePollClaimedUntil sets the "poll_claimed_until" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdatePollClaimedUntil() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdatePollClaimedUntil()
	})
}

// ClearPollClaimedUntil clears the value of the "poll_claimed_until" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearPollClaimedUntil() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearPollClaimedUntil()
	})
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetLastPolledAt(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetLastPolledAt(v)
	})
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateLastPolledAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateLastPolledAt()
	})
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearLastPolledAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearLastPolledAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetUpdatedAt(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateUpdatedAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetStartedAt(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateStartedAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearStartedAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetFinishedAt(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateFinishedAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearFinishedAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) SetSettledAt(v time.Time) *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *BaiduVODVideoTaskUpsertBulk) UpdateSettledAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *BaiduVODVideoTaskUpsertBulk) ClearSettledAt() *BaiduVODVideoTaskUpsertBulk {
	return u.Update(func(s *BaiduVODVideoTaskUpsert) {
		s.ClearSettledAt()
	})
}

// Exec executes the query.
func (u *BaiduVODVideoTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BaiduVODVideoTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BaiduVODVideoTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BaiduVODVideoTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
