// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/baiduvodvideotask"
)

// BaiduVODVideoTask is the model entity for the BaiduVODVideoTask schema.
type BaiduVODVideoTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID string `json:"upstream_task_id,omitempty"`
	// UpstreamRequestID holds the value of the "upstream_request_id" field.
	UpstreamRequestID *string `json:"upstream_request_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// Capability holds the value of the "capability" field.
	Capability string `json:"capability,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus string `json:"upstream_status,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution string `json:"resolution,omitempty"`
	// Ratio holds the value of the "ratio" field.
	Ratio string `json:"ratio,omitempty"`
	// RequestedDuration holds the value of the "requested_duration" field.
	RequestedDuration int `json:"requested_duration,omitempty"`
	// OutputDuration holds the value of the "output_duration" field.
	OutputDuration int `json:"output_duration,omitempty"`
	// InputVideoDuration holds the value of the "input_video_duration" field.
	InputVideoDuration int `json:"input_video_duration,omitempty"`
	// VideoCount holds the value of the "video_count" field.
	VideoCount int `json:"video_count,omitempty"`
	// EstimatedCost holds the value of the "estimated_cost" field.
	EstimatedCost float64 `json:"estimated_cost,omitempty"`
	// HoldAmount holds the value of the "hold_amount" field.
	HoldAmount float64 `json:"hold_amount,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost *float64 `json:"actual_cost,omitempty"`
	// GroupRateMultiplier holds the value of the "group_rate_multiplier" field.
	GroupRateMultiplier float64 `json:"group_rate_multiplier,omitempty"`
	// VideoRateMultiplier holds the value of the "video_rate_multiplier" field.
	VideoRateMultiplier float64 `json:"video_rate_multiplier,omitempty"`
	// AccountRateMultiplier holds the value of the "account_rate_multiplier" field.
	AccountRateMultiplier float64 `json:"account_rate_multiplier,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// ResultURL holds the value of the "result_url" field.
	ResultURL *string `json:"result_url,omitempty"`
	// ResultExpiresAt holds the value of the "result_expires_at" field.
	ResultExpiresAt *time.Time `json:"result_expires_at,omitempty"`
	// LastErrorCode holds the value of the "last_error_code" field.
	LastErrorCode *string `json:"last_error_code,omitempty"`
	// LastErrorMessage holds the value of the "last_error_message" field.
	LastErrorMessage *string `json:"last_error_message,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// NextPollAt holds the value of the "next_poll_at" field.
	NextPollAt time.Time `json:"next_poll_at,omitempty"`
	// PollClaimedUntil holds the value of the "poll_claimed_until" field.
	PollClaimedUntil *time.Time `json:"poll_claimed_until,omitempty"`
	// LastPolledAt holds the value of the "last_polled_at" field.
	LastPolledAt *time.Time `json:"last_polled_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt time.Time `json:"submitted_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt    *time.Time `json:"settled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BaiduVODVideoTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case baiduvodvideotask.FieldEstimatedCost, baiduvodvideotask.FieldHoldAmount, baiduvodvideotask.FieldActualCost, baiduvodvideotask.FieldGroupRateMultiplier, baiduvodvideotask.FieldVideoRateMultiplier, baiduvodvideotask.FieldAccountRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case baiduvodvideotask.FieldID, baiduvodvideotask.FieldUserID, baiduvodvideotask.FieldAPIKeyID, baiduvodvideotask.FieldAccountID, baiduvodvideotask.FieldGroupID, baiduvodvideotask.FieldRequestedDuration, baiduvodvideotask.FieldOutputDuration, baiduvodvideotask.FieldInputVideoDuration, baiduvodvideotask.FieldVideoCount, baiduvodvideotask.FieldRetryCount, baiduvodvideotask.FieldVersion:
			values[i] = new(sql.NullInt64)
		case baiduvodvideotask.FieldPlatform, baiduvodvideotask.FieldProvider, baiduvodvideotask.FieldTaskID, baiduvodvideotask.FieldUpstreamTaskID, baiduvodvideotask.FieldUpstreamRequestID, baiduvodvideotask.FieldModel, baiduvodvideotask.FieldUpstreamModel, baiduvodvideotask.FieldCapability, baiduvodvideotask.FieldStatus, baiduvodvideotask.FieldUpstreamStatus, baiduvodvideotask.FieldResolution, baiduvodvideotask.FieldRatio, baiduvodvideotask.FieldRequestHash, baiduvodvideotask.FieldResultURL, baiduvodvideotask.FieldLastErrorCode, baiduvodvideotask.FieldLastErrorMessage:
			values[i] = new(sql.NullString)
		case baiduvodvideotask.FieldResultExpiresAt, baiduvodvideotask.FieldNextPollAt, baiduvodvideotask.FieldPollClaimedUntil, baiduvodvideotask.FieldLastPolledAt, baiduvodvideotask.FieldCreatedAt, baiduvodvideotask.FieldUpdatedAt, baiduvodvideotask.FieldSubmittedAt, baiduvodvideotask.FieldStartedAt, baiduvodvideotask.FieldFinishedAt, baiduvodvideotask.FieldSettledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BaiduVODVideoTask fields.
func (_m *BaiduVODVideoTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case baiduvodvideotask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case baiduvodvideotask.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case baiduvodvideotask.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case baiduvodvideotask.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case baiduvodvideotask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = value.String
			}
		case baiduvodvideotask.FieldUpstreamRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_id", values[i])
			} else if value.Valid {
				_m.UpstreamRequestID = new(string)
				*_m.UpstreamRequestID = value.String
			}
		case baiduvodvideotask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case baiduvodvideotask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case baiduvodvideotask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case baiduvodvideotask.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case baiduvodvideotask.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case baiduvodvideotask.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case baiduvodvideotask.FieldCapability:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capability", values[i])
			} else if value.Valid {
				_m.Capability = value.String
			}
		case baiduvodvideotask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case baiduvodvideotask.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				_m.UpstreamStatus = value.String
			}
		case baiduvodvideotask.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = value.String
			}
		case baiduvodvideotask.FieldRatio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ratio", values[i])
			} else if value.Valid {
				_m.Ratio = value.String
			}
		case baiduvodvideotask.FieldRequestedDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_duration", values[i])
			} else if value.Valid {
				_m.RequestedDuration = int(value.Int64)
			}
		case baiduvodvideotask.FieldOutputDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_duration", values[i])
			} else if value.Valid {
				_m.OutputDuration = int(value.Int64)
			}
		case baiduvodvideotask.FieldInputVideoDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_video_duration", values[i])
			} else if value.Valid {
				_m.InputVideoDuration = int(value.Int64)
			}
		case baiduvodvideotask.FieldVideoCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_count", values[i])
			} else if value.Valid {
				_m.VideoCount = int(value.Int64)
			}
		case baiduvodvideotask.FieldEstimatedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost", values[i])
			} else if value.Valid {
				_m.EstimatedCost = value.Float64
			}
		case baiduvodvideotask.FieldHoldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hold_amount", values[i])
			} else if value.Valid {
				_m.HoldAmount = value.Float64
			}
		case baiduvodvideotask.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = new(float64)
				*_m.ActualCost = value.Float64
			}
		case baiduvodvideotask.FieldGroupRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field group_rate_multiplier", values[i])
			} else if value.Valid {
				_m.GroupRateMultiplier = value.Float64
			}
		case baiduvodvideotask.FieldVideoRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field video_rate_multiplier", values[i])
			} else if value.Valid {
				_m.VideoRateMultiplier = value.Float64
			}
		case baiduvodvideotask.FieldAccountRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field account_rate_multiplier", values[i])
			} else if value.Valid {
				_m.AccountRateMultiplier = value.Float64
			}
		case baiduvodvideotask.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case baiduvodvideotask.FieldResultURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_url", values[i])
			} else if value.Valid {
				_m.ResultURL = new(string)
				*_m.ResultURL = value.String
			}
		case baiduvodvideotask.FieldResultExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field result_expires_at", values[i])
			} else if value.Valid {
				_m.ResultExpiresAt = new(time.Time)
				*_m.ResultExpiresAt = value.Time
			}
		case baiduvodvideotask.FieldLastErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_code", values[i])
			} else if value.Valid {
				_m.LastErrorCode = new(string)
				*_m.LastErrorCode = value.String
			}
		case baiduvodvideotask.FieldLastErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_message", values[i])
			} else if value.Valid {
				_m.LastErrorMessage = new(string)
				*_m.LastErrorMessage = value.String
			}
		case baiduvodvideotask.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case baiduvodvideotask.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case baiduvodvideotask.FieldNextPollAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_poll_at", values[i])
			} else if value.Valid {
				_m.NextPollAt = value.Time
			}
		case baiduvodvideotask.FieldPollClaimedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field poll_claimed_until", values[i])
			} else if value.Valid {
				_m.PollClaimedUntil = new(time.Time)
				*_m.PollClaimedUntil = value.Time
			}
		case baiduvodvideotask.FieldLastPolledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_polled_at", values[i])
			} else if value.Valid {
				_m.LastPolledAt = new(time.Time)
				*_m.LastPolledAt = value.Time
			}
		case baiduvodvideotask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case baiduvodvideotask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case baiduvodvideotask.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = value.Time
			}
		case baiduvodvideotask.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case baiduvodvideotask.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case baiduvodvideotask.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BaiduVODVideoTask.
// This includes values selected through modifiers, order, etc.
func (_m *BaiduVODVideoTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BaiduVODVideoTask.
// Note that you need to call BaiduVODVideoTask.Unwrap() before calling this method if this BaiduVODVideoTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BaiduVODVideoTask) Update() *BaiduVODVideoTaskUpdateOne {
	return NewBaiduVODVideoTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BaiduVODVideoTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BaiduVODVideoTask) Unwrap() *BaiduVODVideoTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BaiduVODVideoTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BaiduVODVideoTask) String() string {
	var builder strings.Builder
	builder.WriteString("BaiduVODVideoTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("upstream_task_id=")
	builder.WriteString(_m.UpstreamTaskID)
	builder.WriteString(", ")
	if v := _m.UpstreamRequestID; v != nil {
		builder.WriteString("upstream_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("capability=")
	builder.WriteString(_m.Capability)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("upstream_status=")
	builder.WriteString(_m.UpstreamStatus)
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(_m.Resolution)
	builder.WriteString(", ")
	builder.WriteString("ratio=")
	builder.WriteString(_m.Ratio)
	builder.WriteString(", ")
	builder.WriteString("requested_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedDuration))
	builder.WriteString(", ")
	builder.WriteString("output_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputDuration))
	builder.WriteString(", ")
	builder.WriteString("input_video_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputVideoDuration))
	builder.WriteString(", ")
	builder.WriteString("video_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoCount))
	builder.WriteString(", ")
	builder.WriteString("estimated_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedCost))
	builder.WriteString(", ")
	builder.WriteString("hold_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.HoldAmount))
	builder.WriteString(", ")
	if v := _m.ActualCost; v != nil {
		builder.WriteString("actual_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("group_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("video_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("account_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	if v := _m.ResultURL; v != nil {
		builder.WriteString("result_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultExpiresAt; v != nil {
		builder.WriteString("result_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastErrorCode; v != nil {
		builder.WriteString("last_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorMessage; v != nil {
		builder.WriteString("last_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("next_poll_at=")
	builder.WriteString(_m.NextPollAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PollClaimedUntil; v != nil {
		builder.WriteString("poll_claimed_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastPolledAt; v != nil {
		builder.WriteString("last_polled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(_m.SubmittedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BaiduVODVideoTasks is a parsable slice of BaiduVODVideoTask.
type BaiduVODVideoTasks []*BaiduVODVideoTask
