// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/baiduvodvideotask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BaiduVODVideoTaskDelete is the builder for deleting a BaiduVODVideoTask entity.
type BaiduVODVideoTaskDelete struct {
	config
	hooks    []Hook
	mutation *BaiduVODVideoTaskMutation
}

// Where appends a list predicates to the BaiduVODVideoTaskDelete builder.
func (_d *BaiduVODVideoTaskDelete) Where(ps ...predicate.BaiduVODVideoTask) *BaiduVODVideoTaskDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BaiduVODVideoTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BaiduVODVideoTaskDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BaiduVODVideoTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(baiduvodvideotask.Table, sqlgraph.NewFieldSpec(baiduvodvideotask.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BaiduVODVideoTaskDeleteOne is the builder for deleting a single BaiduVODVideoTask entity.
type BaiduVODVideoTaskDeleteOne struct {
	_d *BaiduVODVideoTaskDelete
}

// Where appends a list predicates to the BaiduVODVideoTaskDelete builder.
func (_d *BaiduVODVideoTaskDeleteOne) Where(ps ...predicate.BaiduVODVideoTask) *BaiduVODVideoTaskDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BaiduVODVideoTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{baiduvodvideotask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BaiduVODVideoTaskDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
