// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/baiduvodvideotask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BaiduVODVideoTaskUpdate is the builder for updating BaiduVODVideoTask entities.
type BaiduVODVideoTaskUpdate struct {
	config
	hooks    []Hook
	mutation *BaiduVODVideoTaskMutation
}

// Where appends a list predicates to the BaiduVODVideoTaskUpdate builder.
func (_u *BaiduVODVideoTaskUpdate) Where(ps ...predicate.BaiduVODVideoTask) *BaiduVODVideoTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *BaiduVODVideoTaskUpdate) SetUpstreamRequestID(v string) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableUpstreamRequestID(v *string) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *BaiduVODVideoTaskUpdate) ClearUpstreamRequestID() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BaiduVODVideoTaskUpdate) SetStatus(v string) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableStatus(v *string) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *BaiduVODVideoTaskUpdate) SetUpstreamStatus(v string) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableUpstreamStatus(v *string) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// SetOutputDuration sets the "output_duration" field.
func (_u *BaiduVODVideoTaskUpdate) SetOutputDuration(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.ResetOutputDuration()
	_u.mutation.SetOutputDuration(v)
	return _u
}

// SetNillableOutputDuration sets the "output_duration" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableOutputDuration(v *int) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetOutputDuration(*v)
	}
	return _u
}

// AddOutputDuration adds value to the "output_duration" field.
func (_u *BaiduVODVideoTaskUpdate) AddOutputDuration(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.AddOutputDuration(v)
	return _u
}

// SetInputVideoDuration sets the "input_video_duration" field.
func (_u *BaiduVODVideoTaskUpdate) SetInputVideoDuration(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.ResetInputVideoDuration()
	_u.mutation.SetInputVideoDuration(v)
	return _u
}

// SetNillableInputVideoDuration sets the "input_video_duration" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableInputVideoDuration(v *int) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetInputVideoDuration(*v)
	}
	return _u
}

// AddInputVideoDuration adds value to the "input_video_duration" field.
func (_u *BaiduVODVideoTaskUpdate) AddInputVideoDuration(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.AddInputVideoDuration(v)
	return _u
}

// SetVideoCount sets the "video_count" field.
func (_u *BaiduVODVideoTaskUpdate) SetVideoCount(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.ResetVideoCount()
	_u.mutation.SetVideoCount(v)
	return _u
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableVideoCount(v *int) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetVideoCount(*v)
	}
	return _u
}

// AddVideoCount adds value to the "video_count" field.
func (_u *BaiduVODVideoTaskUpdate) AddVideoCount(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.AddVideoCount(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *BaiduVODVideoTaskUpdate) SetActualCost(v float64) *BaiduVODVideoTaskUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableActualCost(v *float64) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *BaiduVODVideoTaskUpdate) AddActualCost(v float64) *BaiduVODVideoTaskUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *BaiduVODVideoTaskUpdate) ClearActualCost() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearActualCost()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *BaiduVODVideoTaskUpdate) SetResultURL(v string) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableResultURL(v *string) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *BaiduVODVideoTaskUpdate) ClearResultURL() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultExpiresAt sets the "result_expires_at" field.
func (_u *BaiduVODVideoTaskUpdate) SetResultExpiresAt(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetResultExpiresAt(v)
	return _u
}

// SetNillableResultExpiresAt sets the "result_expires_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableResultExpiresAt(v *time.Time) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetResultExpiresAt(*v)
	}
	return _u
}

// ClearResultExpiresAt clears the value of the "result_expires_at" field.
func (_u *BaiduVODVideoTaskUpdate) ClearResultExpiresAt() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearResultExpiresAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *BaiduVODVideoTaskUpdate) SetLastErrorCode(v string) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableLastErrorCode(v *string) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *BaiduVODVideoTaskUpdate) ClearLastErrorCode() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *BaiduVODVideoTaskUpdate) SetLastErrorMessage(v string) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableLastErrorMessage(v *string) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *BaiduVODVideoTaskUpdate) ClearLastErrorMessage() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *BaiduVODVideoTaskUpdate) SetRetryCount(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableRetryCount(v *int) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *BaiduVODVideoTaskUpdate) AddRetryCount(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *BaiduVODVideoTaskUpdate) SetVersion(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableVersion(v *int) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *BaiduVODVideoTaskUpdate) AddVersion(v int) *BaiduVODVideoTaskUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *BaiduVODVideoTaskUpdate) SetNextPollAt(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableNextPollAt(v *time.Time) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// SetPollClaimedUntil sets the "poll_claimed_until" field.
func (_u *BaiduVODVideoTaskUpdate) SetPollClaimedUntil(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetPollClaimedUntil(v)
	return _u
}

// SetNillablePollClaimedUntil sets the "poll_claimed_until" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillablePollClaimedUntil(v *time.Time) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetPollClaimedUntil(*v)
	}
	return _u
}

// ClearPollClaimedUntil clears the value of the "poll_claimed_until" field.
func (_u *BaiduVODVideoTaskUpdate) ClearPollClaimedUntil() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearPollClaimedUntil()
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *BaiduVODVideoTaskUpdate) SetLastPolledAt(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableLastPolledAt(v *time.Time) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *BaiduVODVideoTaskUpdate) ClearLastPolledAt() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BaiduVODVideoTaskUpdate) SetUpdatedAt(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *BaiduVODVideoTaskUpdate) SetStartedAt(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableStartedAt(v *time.Time) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *BaiduVODVideoTaskUpdate) ClearStartedAt() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *BaiduVODVideoTaskUpdate) SetFinishedAt(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableFinishedAt(v *time.Time) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *BaiduVODVideoTaskUpdate) ClearFinishedAt() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *BaiduVODVideoTaskUpdate) SetSettledAt(v time.Time) *BaiduVODVideoTaskUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdate) SetNillableSettledAt(v *time.Time) *BaiduVODVideoTaskUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *BaiduVODVideoTaskUpdate) ClearSettledAt() *BaiduVODVideoTaskUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the BaiduVODVideoTaskMutation object of the builder.
func (_u *BaiduVODVideoTaskUpdate) Mutation() *BaiduVODVideoTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BaiduVODVideoTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BaiduVODVideoTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BaiduVODVideoTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BaiduVODVideoTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BaiduVODVideoTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := baiduvodvideotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BaiduVODVideoTaskUpdate) check() error {
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := baiduvodvideotask.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := baiduvodvideotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := baiduvodvideotask.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := baiduvodvideotask.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *BaiduVODVideoTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(baiduvodvideotask.Table, baiduvodvideotask.Columns, sqlgraph.NewFieldSpec(baiduvodvideotask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(baiduvodvideotask.FieldUpstreamRequestID, field.TypeString)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(baiduvodvideotask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(baiduvodvideotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputDuration(); ok {
		_spec.SetField(baiduvodvideotask.FieldOutputDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputDuration(); ok {
		_spec.AddField(baiduvodvideotask.FieldOutputDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputVideoDuration(); ok {
		_spec.SetField(baiduvodvideotask.FieldInputVideoDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputVideoDuration(); ok {
		_spec.AddField(baiduvodvideotask.FieldInputVideoDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoCount(); ok {
		_spec.SetField(baiduvodvideotask.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoCount(); ok {
		_spec.AddField(baiduvodvideotask.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(baiduvodvideotask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(baiduvodvideotask.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(baiduvodvideotask.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(baiduvodvideotask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(baiduvodvideotask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultExpiresAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldResultExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ResultExpiresAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldResultExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(baiduvodvideotask.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(baiduvodvideotask.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(baiduvodvideotask.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(baiduvodvideotask.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(baiduvodvideotask.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(baiduvodvideotask.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldNextPollAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PollClaimedUntil(); ok {
		_spec.SetField(baiduvodvideotask.FieldPollClaimedUntil, field.TypeTime, value)
	}
	if _u.mutation.PollClaimedUntilCleared() {
		_spec.ClearField(baiduvodvideotask.FieldPollClaimedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldLastPolledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldSettledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{baiduvodvideotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BaiduVODVideoTaskUpdateOne is the builder for updating a single BaiduVODVideoTask entity.
type BaiduVODVideoTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BaiduVODVideoTaskMutation
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetUpstreamRequestID(v string) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableUpstreamRequestID(v *string) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearUpstreamRequestID() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetStatus(v string) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableStatus(v *string) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetUpstreamStatus(v string) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableUpstreamStatus(v *string) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// SetOutputDuration sets the "output_duration" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetOutputDuration(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ResetOutputDuration()
	_u.mutation.SetOutputDuration(v)
	return _u
}

// SetNillableOutputDuration sets the "output_duration" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableOutputDuration(v *int) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetOutputDuration(*v)
	}
	return _u
}

// AddOutputDuration adds value to the "output_duration" field.
func (_u *BaiduVODVideoTaskUpdateOne) AddOutputDuration(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.AddOutputDuration(v)
	return _u
}

// SetInputVideoDuration sets the "input_video_duration" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetInputVideoDuration(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ResetInputVideoDuration()
	_u.mutation.SetInputVideoDuration(v)
	return _u
}

// SetNillableInputVideoDuration sets the "input_video_duration" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableInputVideoDuration(v *int) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetInputVideoDuration(*v)
	}
	return _u
}

// AddInputVideoDuration adds value to the "input_video_duration" field.
func (_u *BaiduVODVideoTaskUpdateOne) AddInputVideoDuration(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.AddInputVideoDuration(v)
	return _u
}

// SetVideoCount sets the "video_count" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetVideoCount(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ResetVideoCount()
	_u.mutation.SetVideoCount(v)
	return _u
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableVideoCount(v *int) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetVideoCount(*v)
	}
	return _u
}

// AddVideoCount adds value to the "video_count" field.
func (_u *BaiduVODVideoTaskUpdateOne) AddVideoCount(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.AddVideoCount(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetActualCost(v float64) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableActualCost(v *float64) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *BaiduVODVideoTaskUpdateOne) AddActualCost(v float64) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearActualCost() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearActualCost()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetResultURL(v string) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableResultURL(v *string) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearResultURL() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultExpiresAt sets the "result_expires_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetResultExpiresAt(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetResultExpiresAt(v)
	return _u
}

// SetNillableResultExpiresAt sets the "result_expires_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableResultExpiresAt(v *time.Time) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetResultExpiresAt(*v)
	}
	return _u
}

// ClearResultExpiresAt clears the value of the "result_expires_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearResultExpiresAt() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearResultExpiresAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetLastErrorCode(v string) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableLastErrorCode(v *string) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearLastErrorCode() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetLastErrorMessage(v string) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableLastErrorMessage(v *string) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearLastErrorMessage() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetRetryCount(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableRetryCount(v *int) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *BaiduVODVideoTaskUpdateOne) AddRetryCount(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetVersion(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableVersion(v *int) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *BaiduVODVideoTaskUpdateOne) AddVersion(v int) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetNextPollAt(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableNextPollAt(v *time.Time) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// SetPollClaimedUntil sets the "poll_claimed_until" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetPollClaimedUntil(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetPollClaimedUntil(v)
	return _u
}

// SetNillablePollClaimedUntil sets the "poll_claimed_until" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillablePollClaimedUntil(v *time.Time) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetPollClaimedUntil(*v)
	}
	return _u
}

// ClearPollClaimedUntil clears the value of the "poll_claimed_until" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearPollClaimedUntil() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearPollClaimedUntil()
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetLastPolledAt(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableLastPolledAt(v *time.Time) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearLastPolledAt() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetUpdatedAt(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetStartedAt(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableStartedAt(v *time.Time) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearStartedAt() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetFinishedAt(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearFinishedAt() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) SetSettledAt(v time.Time) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *BaiduVODVideoTaskUpdateOne) SetNillableSettledAt(v *time.Time) *BaiduVODVideoTaskUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *BaiduVODVideoTaskUpdateOne) ClearSettledAt() *BaiduVODVideoTaskUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the BaiduVODVideoTaskMutation object of the builder.
func (_u *BaiduVODVideoTaskUpdateOne) Mutation() *BaiduVODVideoTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the BaiduVODVideoTaskUpdate builder.
func (_u *BaiduVODVideoTaskUpdateOne) Where(ps ...predicate.BaiduVODVideoTask) *BaiduVODVideoTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BaiduVODVideoTaskUpdateOne) Select(field string, fields ...string) *BaiduVODVideoTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BaiduVODVideoTask entity.
func (_u *BaiduVODVideoTaskUpdateOne) Save(ctx context.Context) (*BaiduVODVideoTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BaiduVODVideoTaskUpdateOne) SaveX(ctx context.Context) *BaiduVODVideoTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BaiduVODVideoTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BaiduVODVideoTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BaiduVODVideoTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := baiduvodvideotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BaiduVODVideoTaskUpdateOne) check() error {
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := baiduvodvideotask.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := baiduvodvideotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := baiduvodvideotask.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := baiduvodvideotask.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "BaiduVODVideoTask.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *BaiduVODVideoTaskUpdateOne) sqlSave(ctx context.Context) (_node *BaiduVODVideoTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(baiduvodvideotask.Table, baiduvodvideotask.Columns, sqlgraph.NewFieldSpec(baiduvodvideotask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BaiduVODVideoTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, baiduvodvideotask.FieldID)
		for _, f := range fields {
			if !baiduvodvideotask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != baiduvodvideotask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(baiduvodvideotask.FieldUpstreamRequestID, field.TypeString)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(baiduvodvideotask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(baiduvodvideotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpstreamStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputDuration(); ok {
		_spec.SetField(baiduvodvideotask.FieldOutputDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputDuration(); ok {
		_spec.AddField(baiduvodvideotask.FieldOutputDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputVideoDuration(); ok {
		_spec.SetField(baiduvodvideotask.FieldInputVideoDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputVideoDuration(); ok {
		_spec.AddField(baiduvodvideotask.FieldInputVideoDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoCount(); ok {
		_spec.SetField(baiduvodvideotask.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoCount(); ok {
		_spec.AddField(baiduvodvideotask.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(baiduvodvideotask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(baiduvodvideotask.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(baiduvodvideotask.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(baiduvodvideotask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(baiduvodvideotask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultExpiresAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldResultExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ResultExpiresAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldResultExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(baiduvodvideotask.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(baiduvodvideotask.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(baiduvodvideotask.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(baiduvodvideotask.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(baiduvodvideotask.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(baiduvodvideotask.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldNextPollAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PollClaimedUntil(); ok {
		_spec.SetField(baiduvodvideotask.FieldPollClaimedUntil, field.TypeTime, value)
	}
	if _u.mutation.PollClaimedUntilCleared() {
		_spec.ClearField(baiduvodvideotask.FieldPollClaimedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldLastPolledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(baiduvodvideotask.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(baiduvodvideotask.FieldSettledAt, field.TypeTime)
	}
	_node = &BaiduVODVideoTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{baiduvodvideotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
