// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/invoiceitem"
)

// InvoiceCreate is the builder for creating a Invoice entity.
type InvoiceCreate struct {
	config
	mutation *InvoiceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceCreate) SetUserID(v int64) *InvoiceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInvoiceNo sets the "invoice_no" field.
func (_c *InvoiceCreate) SetInvoiceNo(v string) *InvoiceCreate {
	_c.mutation.SetInvoiceNo(v)
	return _c
}

// SetEntityType sets the "entity_type" field.
func (_c *InvoiceCreate) SetEntityType(v string) *InvoiceCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableEntityType(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetEntityType(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *InvoiceCreate) SetTitle(v string) *InvoiceCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetTaxID sets the "tax_id" field.
func (_c *InvoiceCreate) SetTaxID(v string) *InvoiceCreate {
	_c.mutation.SetTaxID(v)
	return _c
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableTaxID(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetTaxID(*v)
	}
	return _c
}

// SetDeliveryEmail sets the "delivery_email" field.
func (_c *InvoiceCreate) SetDeliveryEmail(v string) *InvoiceCreate {
	_c.mutation.SetDeliveryEmail(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *InvoiceCreate) SetNotes(v string) *InvoiceCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableNotes(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceCreate) SetAmount(v float64) *InvoiceCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableAmount(v *float64) *InvoiceCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceCreate) SetStatus(v string) *InvoiceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableStatus(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIssuedInvoiceNo sets the "issued_invoice_no" field.
func (_c *InvoiceCreate) SetIssuedInvoiceNo(v string) *InvoiceCreate {
	_c.mutation.SetIssuedInvoiceNo(v)
	return _c
}

// SetNillableIssuedInvoiceNo sets the "issued_invoice_no" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableIssuedInvoiceNo(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetIssuedInvoiceNo(*v)
	}
	return _c
}

// SetIssuedFileURL sets the "issued_file_url" field.
func (_c *InvoiceCreate) SetIssuedFileURL(v string) *InvoiceCreate {
	_c.mutation.SetIssuedFileURL(v)
	return _c
}

// SetNillableIssuedFileURL sets the "issued_file_url" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableIssuedFileURL(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetIssuedFileURL(*v)
	}
	return _c
}

// SetRejectReason sets the "reject_reason" field.
func (_c *InvoiceCreate) SetRejectReason(v string) *InvoiceCreate {
	_c.mutation.SetRejectReason(v)
	return _c
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableRejectReason(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetRejectReason(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *InvoiceCreate) SetReviewedBy(v int64) *InvoiceCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableReviewedBy(v *int64) *InvoiceCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *InvoiceCreate) SetReviewedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableReviewedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceCreate) SetCreatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCreatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceCreate) SetUpdatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddItemIDs adds the "items" edge to the InvoiceItem entity by IDs.
func (_c *InvoiceCreate) AddItemIDs(ids ...int64) *InvoiceCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the InvoiceItem entity.
func (_c *InvoiceCreate) AddItems(v ...*InvoiceItem) *InvoiceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_c *InvoiceCreate) Mutation() *InvoiceMutation {
	return _c.mutation
}

// Save creates the Invoice in the database.
func (_c *InvoiceCreate) Save(ctx context.Context) (*Invoice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceCreate) SaveX(ctx context.Context) *Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceCreate) defaults() {
	if _, ok := _c.mutation.EntityType(); !ok {
		v := invoice.DefaultEntityType
		_c.mutation.SetEntityType(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := invoice.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoice.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Invoice.user_id"`)}
	}
	if _, ok := _c.mutation.InvoiceNo(); !ok {
		return &ValidationError{Name: "invoice_no", err: errors.New(`ent: missing required field "Invoice.invoice_no"`)}
	}
	if v, ok := _c.mutation.InvoiceNo(); ok {
		if err := invoice.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.invoice_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "Invoice.entity_type"`)}
	}
	if v, ok := _c.mutation.EntityType(); ok {
		if err := invoice.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Invoice.entity_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Invoice.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := invoice.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Invoice.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaxID(); ok {
		if err := invoice.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "Invoice.tax_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeliveryEmail(); !ok {
		return &ValidationError{Name: "delivery_email", err: errors.New(`ent: missing required field "Invoice.delivery_email"`)}
	}
	if v, ok := _c.mutation.DeliveryEmail(); ok {
		if err := invoice.DeliveryEmailValidator(v); err != nil {
			return &ValidationError{Name: "delivery_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.delivery_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Invoice.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invoice.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IssuedInvoiceNo(); ok {
		if err := invoice.IssuedInvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "issued_invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.issued_invoice_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IssuedFileURL(); ok {
		if err := invoice.IssuedFileURLValidator(v); err != nil {
			return &ValidationError{Name: "issued_file_url", err: fmt.Errorf(`ent: validator failed for field "Invoice.issued_file_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Invoice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Invoice.updated_at"`)}
	}
	return nil
}

func (_c *InvoiceCreate) sqlSave(ctx context.Context) (*Invoice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceCreate) createSpec() (*Invoice, *sqlgraph.CreateSpec) {
	var (
		_node = &Invoice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoice.Table, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(invoice.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.InvoiceNo(); ok {
		_spec.SetField(invoice.FieldInvoiceNo, field.TypeString, value)
		_node.InvoiceNo = value
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(invoice.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(invoice.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.TaxID(); ok {
		_spec.SetField(invoice.FieldTaxID, field.TypeString, value)
		_node.TaxID = &value
	}
	if value, ok := _c.mutation.DeliveryEmail(); ok {
		_spec.SetField(invoice.FieldDeliveryEmail, field.TypeString, value)
		_node.DeliveryEmail = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(invoice.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IssuedInvoiceNo(); ok {
		_spec.SetField(invoice.FieldIssuedInvoiceNo, field.TypeString, value)
		_node.IssuedInvoiceNo = &value
	}
	if value, ok := _c.mutation.IssuedFileURL(); ok {
		_spec.SetField(invoice.FieldIssuedFileURL, field.TypeString, value)
		_node.IssuedFileURL = &value
	}
	if value, ok := _c.mutation.RejectReason(); ok {
		_spec.SetField(invoice.FieldRejectReason, field.TypeString, value)
		_node.RejectReason = &value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(invoice.FieldReviewedBy, field.TypeInt64, value)
		_node.ReviewedBy = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(invoice.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertOne {
	_c.conflict = opts
	return &InvoiceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflictColumns(columns ...string) *InvoiceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceUpsertOne is the builder for "upsert"-ing
	//  one Invoice node.
	InvoiceUpsertOne struct {
		create *InvoiceCreate
	}

	// InvoiceUpsert is the "OnConflict" setter.
	InvoiceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceUpsert) SetUserID(v int64) *InvoiceUpsert {
	u.Set(invoice.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUserID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceUpsert) AddUserID(v int64) *InvoiceUpsert {
	u.Add(invoice.FieldUserID, v)
	return u
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceUpsert) SetInvoiceNo(v string) *InvoiceUpsert {
	u.Set(invoice.FieldInvoiceNo, v)
	return u
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateInvoiceNo() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldInvoiceNo)
	return u
}

// SetEntityType sets the "entity_type" field.
func (u *InvoiceUpsert) SetEntityType(v string) *InvoiceUpsert {
	u.Set(invoice.FieldEntityType, v)
	return u
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateEntityType() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldEntityType)
	return u
}

// SetTitle sets the "title" field.
func (u *InvoiceUpsert) SetTitle(v string) *InvoiceUpsert {
	u.Set(invoice.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTitle() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTitle)
	return u
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceUpsert) SetTaxID(v string) *InvoiceUpsert {
	u.Set(invoice.FieldTaxID, v)
	return u
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTaxID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTaxID)
	return u
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceUpsert) ClearTaxID() *InvoiceUpsert {
	u.SetNull(invoice.FieldTaxID)
	return u
}

// SetDeliveryEmail sets the "delivery_email" field.
func (u *InvoiceUpsert) SetDeliveryEmail(v string) *InvoiceUpsert {
	u.Set(invoice.FieldDeliveryEmail, v)
	return u
}

// UpdateDeliveryEmail sets the "delivery_email" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateDeliveryEmail() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldDeliveryEmail)
	return u
}

// SetNotes sets the "notes" field.
func (u *InvoiceUpsert) SetNotes(v string) *InvoiceUpsert {
	u.Set(invoice.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateNotes() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *InvoiceUpsert) ClearNotes() *InvoiceUpsert {
	u.SetNull(invoice.FieldNotes)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceUpsert) SetAmount(v float64) *InvoiceUpsert {
	u.Set(invoice.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateAmount() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceUpsert) AddAmount(v float64) *InvoiceUpsert {
	u.Add(invoice.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsert) SetStatus(v string) *InvoiceUpsert {
	u.Set(invoice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateStatus() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldStatus)
	return u
}

// SetIssuedInvoiceNo sets the "issued_invoice_no" field.
func (u *InvoiceUpsert) SetIssuedInvoiceNo(v string) *InvoiceUpsert {
	u.Set(invoice.FieldIssuedInvoiceNo, v)
	return u
}

// UpdateIssuedInvoiceNo sets the "issued_invoice_no" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateIssuedInvoiceNo() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldIssuedInvoiceNo)
	return u
}

// ClearIssuedInvoiceNo clears the value of the "issued_invoice_no" field.
func (u *InvoiceUpsert) ClearIssuedInvoiceNo() *InvoiceUpsert {
	u.SetNull(invoice.FieldIssuedInvoiceNo)
	return u
}

// SetIssuedFileURL sets the "issued_file_url" field.
func (u *InvoiceUpsert) SetIssuedFileURL(v string) *InvoiceUpsert {
	u.Set(invoice.FieldIssuedFileURL, v)
	return u
}

// UpdateIssuedFileURL sets the "issued_file_url" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateIssuedFileURL() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldIssuedFileURL)
	return u
}

// ClearIssuedFileURL clears the value of the "issued_file_url" field.
func (u *InvoiceUpsert) ClearIssuedFileURL() *InvoiceUpsert {
	u.SetNull(invoice.FieldIssuedFileURL)
	return u
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceUpsert) SetRejectReason(v string) *InvoiceUpsert {
	u.Set(invoice.FieldRejectReason, v)
	return u
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateRejectReason() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldRejectReason)
	return u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceUpsert) ClearRejectReason() *InvoiceUpsert {
	u.SetNull(invoice.FieldRejectReason)
	return u
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *InvoiceUpsert) SetReviewedBy(v int64) *InvoiceUpsert {
	u.Set(invoice.FieldReviewedBy, v)
	return u
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateReviewedBy() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldReviewedBy)
	return u
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *InvoiceUpsert) AddReviewedBy(v int64) *InvoiceUpsert {
	u.Add(invoice.FieldReviewedBy, v)
	return u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *InvoiceUpsert) ClearReviewedBy() *InvoiceUpsert {
	u.SetNull(invoice.FieldReviewedBy)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceUpsert) SetReviewedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateReviewedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceUpsert) ClearReviewedAt() *InvoiceUpsert {
	u.SetNull(invoice.FieldReviewedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsert) SetUpdatedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUpdatedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertOne) UpdateNewValues() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceUpsertOne) Ignore() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertOne) DoNothing() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreate.OnConflict
// documentation for more info.
func (u *InvoiceUpsertOne) Update(set func(*InvoiceUpsert)) *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceUpsertOne) SetUserID(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceUpsertOne) AddUserID(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUserID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUserID()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceUpsertOne) SetInvoiceNo(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateInvoiceNo() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceNo()
	})
}

// SetEntityType sets the "entity_type" field.
func (u *InvoiceUpsertOne) SetEntityType(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateEntityType() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateEntityType()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceUpsertOne) SetTitle(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTitle() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTitle()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceUpsertOne) SetTaxID(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTaxID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceUpsertOne) ClearTaxID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearTaxID()
	})
}

// SetDeliveryEmail sets the "delivery_email" field.
func (u *InvoiceUpsertOne) SetDeliveryEmail(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDeliveryEmail(v)
	})
}

// UpdateDeliveryEmail sets the "delivery_email" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateDeliveryEmail() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDeliveryEmail()
	})
}

// SetNotes sets the "notes" field.
func (u *InvoiceUpsertOne) SetNotes(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateNotes() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *InvoiceUpsertOne) ClearNotes() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearNotes()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceUpsertOne) SetAmount(v float64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceUpsertOne) AddAmount(v float64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateAmount() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertOne) SetStatus(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateStatus() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetIssuedInvoiceNo sets the "issued_invoice_no" field.
func (u *InvoiceUpsertOne) SetIssuedInvoiceNo(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetIssuedInvoiceNo(v)
	})
}

// UpdateIssuedInvoiceNo sets the "issued_invoice_no" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateIssuedInvoiceNo() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateIssuedInvoiceNo()
	})
}

// ClearIssuedInvoiceNo clears the value of the "issued_invoice_no" field.
func (u *InvoiceUpsertOne) ClearIssuedInvoiceNo() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearIssuedInvoiceNo()
	})
}

// SetIssuedFileURL sets the "issued_file_url" field.
func (u *InvoiceUpsertOne) SetIssuedFileURL(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetIssuedFileURL(v)
	})
}

// UpdateIssuedFileURL sets the "issued_file_url" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateIssuedFileURL() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateIssuedFileURL()
	})
}

// ClearIssuedFileURL clears the value of the "issued_file_url" field.
func (u *InvoiceUpsertOne) ClearIssuedFileURL() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearIssuedFileURL()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceUpsertOne) SetRejectReason(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateRejectReason() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceUpsertOne) ClearRejectReason() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearRejectReason()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *InvoiceUpsertOne) SetReviewedBy(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *InvoiceUpsertOne) AddReviewedBy(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateReviewedBy() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *InvoiceUpsertOne) ClearReviewedBy() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceUpsertOne) SetReviewedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateReviewedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceUpsertOne) ClearReviewedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReviewedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertOne) SetUpdatedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUpdatedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceCreateBulk is the builder for creating many Invoice entities in bulk.
type InvoiceCreateBulk struct {
	config
	err      error
	builders []*InvoiceCreate
	conflict []sql.ConflictOption
}

// Save creates the Invoice entities in the database.
func (_c *InvoiceCreateBulk) Save(ctx context.Context) ([]*Invoice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invoice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceCreateBulk) SaveX(ctx context.Context) []*Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertBulk {
	_c.conflict = opts
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflictColumns(columns ...string) *InvoiceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// InvoiceUpsertBulk is the builder for "upsert"-ing
// a bulk of Invoice nodes.
type InvoiceUpsertBulk struct {
	create *InvoiceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) UpdateNewValues() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) Ignore() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertBulk) DoNothing() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceUpsertBulk) Update(set func(*InvoiceUpsert)) *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceUpsertBulk) SetUserID(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceUpsertBulk) AddUserID(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUserID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUserID()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceUpsertBulk) SetInvoiceNo(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateInvoiceNo() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceNo()
	})
}

// SetEntityType sets the "entity_type" field.
func (u *InvoiceUpsertBulk) SetEntityType(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateEntityType() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateEntityType()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceUpsertBulk) SetTitle(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTitle() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTitle()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceUpsertBulk) SetTaxID(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTaxID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceUpsertBulk) ClearTaxID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearTaxID()
	})
}

// SetDeliveryEmail sets the "delivery_email" field.
func (u *InvoiceUpsertBulk) SetDeliveryEmail(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDeliveryEmail(v)
	})
}

// UpdateDeliveryEmail sets the "delivery_email" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateDeliveryEmail() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDeliveryEmail()
	})
}

// SetNotes sets the "notes" field.
func (u *InvoiceUpsertBulk) SetNotes(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateNotes() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *InvoiceUpsertBulk) ClearNotes() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearNotes()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceUpsertBulk) SetAmount(v float64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceUpsertBulk) AddAmount(v float64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateAmount() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertBulk) SetStatus(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateStatus() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetIssuedInvoiceNo sets the "issued_invoice_no" field.
func (u *InvoiceUpsertBulk) SetIssuedInvoiceNo(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetIssuedInvoiceNo(v)
	})
}

// UpdateIssuedInvoiceNo sets the "issued_invoice_no" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateIssuedInvoiceNo() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateIssuedInvoiceNo()
	})
}

// ClearIssuedInvoiceNo clears the value of the "issued_invoice_no" field.
func (u *InvoiceUpsertBulk) ClearIssuedInvoiceNo() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearIssuedInvoiceNo()
	})
}

// SetIssuedFileURL sets the "issued_file_url" field.
func (u *InvoiceUpsertBulk) SetIssuedFileURL(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetIssuedFileURL(v)
	})
}

// UpdateIssuedFileURL sets the "issued_file_url" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateIssuedFileURL() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateIssuedFileURL()
	})
}

// ClearIssuedFileURL clears the value of the "issued_file_url" field.
func (u *InvoiceUpsertBulk) ClearIssuedFileURL() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearIssuedFileURL()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceUpsertBulk) SetRejectReason(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateRejectReason() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceUpsertBulk) ClearRejectReason() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearRejectReason()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *InvoiceUpsertBulk) SetReviewedBy(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *InvoiceUpsertBulk) AddReviewedBy(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateReviewedBy() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *InvoiceUpsertBulk) ClearReviewedBy() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceUpsertBulk) SetReviewedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateReviewedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceUpsertBulk) ClearReviewedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReviewedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUpdatedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
