// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/invoiceitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceUpdate is the builder for updating Invoice entities.
type InvoiceUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceMutation
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (_u *InvoiceUpdate) Where(ps ...predicate.Invoice) *InvoiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceUpdate) SetUserID(v int64) *InvoiceUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableUserID(v *int64) *InvoiceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceUpdate) AddUserID(v int64) *InvoiceUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceUpdate) SetInvoiceNo(v string) *InvoiceUpdate {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableInvoiceNo(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *InvoiceUpdate) SetEntityType(v string) *InvoiceUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableEntityType(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceUpdate) SetTitle(v string) *InvoiceUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableTitle(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *InvoiceUpdate) SetTaxID(v string) *InvoiceUpdate {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableTaxID(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// ClearTaxID clears the value of the "tax_id" field.
func (_u *InvoiceUpdate) ClearTaxID() *InvoiceUpdate {
	_u.mutation.ClearTaxID()
	return _u
}

// SetDeliveryEmail sets the "delivery_email" field.
func (_u *InvoiceUpdate) SetDeliveryEmail(v string) *InvoiceUpdate {
	_u.mutation.SetDeliveryEmail(v)
	return _u
}

// SetNillableDeliveryEmail sets the "delivery_email" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableDeliveryEmail(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetDeliveryEmail(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InvoiceUpdate) SetNotes(v string) *InvoiceUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableNotes(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *InvoiceUpdate) ClearNotes() *InvoiceUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceUpdate) SetAmount(v float64) *InvoiceUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableAmount(v *float64) *InvoiceUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceUpdate) AddAmount(v float64) *InvoiceUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceUpdate) SetStatus(v string) *InvoiceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableStatus(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssuedInvoiceNo sets the "issued_invoice_no" field.
func (_u *InvoiceUpdate) SetIssuedInvoiceNo(v string) *InvoiceUpdate {
	_u.mutation.SetIssuedInvoiceNo(v)
	return _u
}

// SetNillableIssuedInvoiceNo sets the "issued_invoice_no" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableIssuedInvoiceNo(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetIssuedInvoiceNo(*v)
	}
	return _u
}

// ClearIssuedInvoiceNo clears the value of the "issued_invoice_no" field.
func (_u *InvoiceUpdate) ClearIssuedInvoiceNo() *InvoiceUpdate {
	_u.mutation.ClearIssuedInvoiceNo()
	return _u
}

// SetIssuedFileURL sets the "issued_file_url" field.
func (_u *InvoiceUpdate) SetIssuedFileURL(v string) *InvoiceUpdate {
	_u.mutation.SetIssuedFileURL(v)
	return _u
}

// SetNillableIssuedFileURL sets the "issued_file_url" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableIssuedFileURL(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetIssuedFileURL(*v)
	}
	return _u
}

// ClearIssuedFileURL clears the value of the "issued_file_url" field.
func (_u *InvoiceUpdate) ClearIssuedFileURL() *InvoiceUpdate {
	_u.mutation.ClearIssuedFileURL()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *InvoiceUpdate) SetRejectReason(v string) *InvoiceUpdate {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableRejectReason(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *InvoiceUpdate) ClearRejectReason() *InvoiceUpdate {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *InvoiceUpdate) SetReviewedBy(v int64) *InvoiceUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableReviewedBy(v *int64) *InvoiceUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *InvoiceUpdate) AddReviewedBy(v int64) *InvoiceUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *InvoiceUpdate) ClearReviewedBy() *InvoiceUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *InvoiceUpdate) SetReviewedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableReviewedAt(v *time.Time) *InvoiceUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *InvoiceUpdate) ClearReviewedAt() *InvoiceUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceUpdate) SetUpdatedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddItemIDs adds the "items" edge to the InvoiceItem entity by IDs.
func (_u *InvoiceUpdate) AddItemIDs(ids ...int64) *InvoiceUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdate) AddItems(v ...*InvoiceItem) *InvoiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_u *InvoiceUpdate) Mutation() *InvoiceMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdate) ClearItems() *InvoiceUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to InvoiceItem entities by IDs.
func (_u *InvoiceUpdate) RemoveItemIDs(ids ...int64) *InvoiceUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to InvoiceItem entities.
func (_u *InvoiceUpdate) RemoveItems(v ...*InvoiceItem) *InvoiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceUpdate) check() error {
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoice.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := invoice.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Invoice.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoice.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Invoice.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := invoice.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "Invoice.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryEmail(); ok {
		if err := invoice.DeliveryEmailValidator(v); err != nil {
			return &ValidationError{Name: "delivery_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.delivery_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedInvoiceNo(); ok {
		if err := invoice.IssuedInvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "issued_invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.issued_invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedFileURL(); ok {
		if err := invoice.IssuedFileURLValidator(v); err != nil {
			return &ValidationError{Name: "issued_file_url", err: fmt.Errorf(`ent: validator failed for field "Invoice.issued_file_url": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoice.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoice.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoice.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(invoice.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoice.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(invoice.FieldTaxID, field.TypeString, value)
	}
	if _u.mutation.TaxIDCleared() {
		_spec.ClearField(invoice.FieldTaxID, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryEmail(); ok {
		_spec.SetField(invoice.FieldDeliveryEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(invoice.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(invoice.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedInvoiceNo(); ok {
		_spec.SetField(invoice.FieldIssuedInvoiceNo, field.TypeString, value)
	}
	if _u.mutation.IssuedInvoiceNoCleared() {
		_spec.ClearField(invoice.FieldIssuedInvoiceNo, field.TypeString)
	}
	if value, ok := _u.mutation.IssuedFileURL(); ok {
		_spec.SetField(invoice.FieldIssuedFileURL, field.TypeString, value)
	}
	if _u.mutation.IssuedFileURLCleared() {
		_spec.ClearField(invoice.FieldIssuedFileURL, field.TypeString)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(invoice.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(invoice.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(invoice.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(invoice.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(invoice.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceUpdateOne is the builder for updating a single Invoice entity.
type InvoiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceUpdateOne) SetUserID(v int64) *InvoiceUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableUserID(v *int64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceUpdateOne) AddUserID(v int64) *InvoiceUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceUpdateOne) SetInvoiceNo(v string) *InvoiceUpdateOne {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableInvoiceNo(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *InvoiceUpdateOne) SetEntityType(v string) *InvoiceUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableEntityType(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceUpdateOne) SetTitle(v string) *InvoiceUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableTitle(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *InvoiceUpdateOne) SetTaxID(v string) *InvoiceUpdateOne {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableTaxID(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// ClearTaxID clears the value of the "tax_id" field.
func (_u *InvoiceUpdateOne) ClearTaxID() *InvoiceUpdateOne {
	_u.mutation.ClearTaxID()
	return _u
}

// SetDeliveryEmail sets the "delivery_email" field.
func (_u *InvoiceUpdateOne) SetDeliveryEmail(v string) *InvoiceUpdateOne {
	_u.mutation.SetDeliveryEmail(v)
	return _u
}

// SetNillableDeliveryEmail sets the "delivery_email" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableDeliveryEmail(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetDeliveryEmail(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InvoiceUpdateOne) SetNotes(v string) *InvoiceUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableNotes(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *InvoiceUpdateOne) ClearNotes() *InvoiceUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceUpdateOne) SetAmount(v float64) *InvoiceUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableAmount(v *float64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceUpdateOne) AddAmount(v float64) *InvoiceUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceUpdateOne) SetStatus(v string) *InvoiceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableStatus(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssuedInvoiceNo sets the "issued_invoice_no" field.
func (_u *InvoiceUpdateOne) SetIssuedInvoiceNo(v string) *InvoiceUpdateOne {
	_u.mutation.SetIssuedInvoiceNo(v)
	return _u
}

// SetNillableIssuedInvoiceNo sets the "issued_invoice_no" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableIssuedInvoiceNo(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetIssuedInvoiceNo(*v)
	}
	return _u
}

// ClearIssuedInvoiceNo clears the value of the "issued_invoice_no" field.
func (_u *InvoiceUpdateOne) ClearIssuedInvoiceNo() *InvoiceUpdateOne {
	_u.mutation.ClearIssuedInvoiceNo()
	return _u
}

// SetIssuedFileURL sets the "issued_file_url" field.
func (_u *InvoiceUpdateOne) SetIssuedFileURL(v string) *InvoiceUpdateOne {
	_u.mutation.SetIssuedFileURL(v)
	return _u
}

// SetNillableIssuedFileURL sets the "issued_file_url" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableIssuedFileURL(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetIssuedFileURL(*v)
	}
	return _u
}

// ClearIssuedFileURL clears the value of the "issued_file_url" field.
func (_u *InvoiceUpdateOne) ClearIssuedFileURL() *InvoiceUpdateOne {
	_u.mutation.ClearIssuedFileURL()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *InvoiceUpdateOne) SetRejectReason(v string) *InvoiceUpdateOne {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableRejectReason(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *InvoiceUpdateOne) ClearRejectReason() *InvoiceUpdateOne {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *InvoiceUpdateOne) SetReviewedBy(v int64) *InvoiceUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableReviewedBy(v *int64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *InvoiceUpdateOne) AddReviewedBy(v int64) *InvoiceUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *InvoiceUpdateOne) ClearReviewedBy() *InvoiceUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *InvoiceUpdateOne) SetReviewedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableReviewedAt(v *time.Time) *InvoiceUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *InvoiceUpdateOne) ClearReviewedAt() *InvoiceUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceUpdateOne) SetUpdatedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddItemIDs adds the "items" edge to the InvoiceItem entity by IDs.
func (_u *InvoiceUpdateOne) AddItemIDs(ids ...int64) *InvoiceUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdateOne) AddItems(v ...*InvoiceItem) *InvoiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_u *InvoiceUpdateOne) Mutation() *InvoiceMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdateOne) ClearItems() *InvoiceUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to InvoiceItem entities by IDs.
func (_u *InvoiceUpdateOne) RemoveItemIDs(ids ...int64) *InvoiceUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to InvoiceItem entities.
func (_u *InvoiceUpdateOne) RemoveItems(v ...*InvoiceItem) *InvoiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (_u *InvoiceUpdateOne) Where(ps ...predicate.Invoice) *InvoiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceUpdateOne) Select(field string, fields ...string) *InvoiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invoice entity.
func (_u *InvoiceUpdateOne) Save(ctx context.Context) (*Invoice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceUpdateOne) SaveX(ctx context.Context) *Invoice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceUpdateOne) check() error {
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoice.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := invoice.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Invoice.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoice.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Invoice.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := invoice.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "Invoice.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryEmail(); ok {
		if err := invoice.DeliveryEmailValidator(v); err != nil {
			return &ValidationError{Name: "delivery_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.delivery_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedInvoiceNo(); ok {
		if err := invoice.IssuedInvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "issued_invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.issued_invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedFileURL(); ok {
		if err := invoice.IssuedFileURLValidator(v); err != nil {
			return &ValidationError{Name: "issued_file_url", err: fmt.Errorf(`ent: validator failed for field "Invoice.issued_file_url": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceUpdateOne) sqlSave(ctx context.Context) (_node *Invoice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invoice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoice.FieldID)
		for _, f := range fields {
			if !invoice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoice.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoice.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoice.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(invoice.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoice.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(invoice.FieldTaxID, field.TypeString, value)
	}
	if _u.mutation.TaxIDCleared() {
		_spec.ClearField(invoice.FieldTaxID, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryEmail(); ok {
		_spec.SetField(invoice.FieldDeliveryEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(invoice.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(invoice.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedInvoiceNo(); ok {
		_spec.SetField(invoice.FieldIssuedInvoiceNo, field.TypeString, value)
	}
	if _u.mutation.IssuedInvoiceNoCleared() {
		_spec.ClearField(invoice.FieldIssuedInvoiceNo, field.TypeString)
	}
	if value, ok := _u.mutation.IssuedFileURL(); ok {
		_spec.SetField(invoice.FieldIssuedFileURL, field.TypeString, value)
	}
	if _u.mutation.IssuedFileURLCleared() {
		_spec.ClearField(invoice.FieldIssuedFileURL, field.TypeString)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(invoice.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(invoice.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(invoice.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(invoice.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(invoice.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invoice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
