// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/invoiceitem"
)

// InvoiceItem is the model entity for the InvoiceItem schema.
type InvoiceItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InvoiceID holds the value of the "invoice_id" field.
	InvoiceID int64 `json:"invoice_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// OrderCreatedAt holds the value of the "order_created_at" field.
	OrderCreatedAt *time.Time `json:"order_created_at,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceItemQuery when eager-loading is set.
	Edges        InvoiceItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceItemEdges holds the relations/edges for other nodes in the graph.
type InvoiceItemEdges struct {
	// Invoice holds the value of the invoice edge.
	Invoice *Invoice `json:"invoice,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InvoiceOrErr returns the Invoice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceItemEdges) InvoiceOrErr() (*Invoice, error) {
	if e.Invoice != nil {
		return e.Invoice, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invoice.Label}
	}
	return nil, &NotLoadedError{edge: "invoice"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoiceitem.FieldActive:
			values[i] = new(sql.NullBool)
		case invoiceitem.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case invoiceitem.FieldID, invoiceitem.FieldInvoiceID, invoiceitem.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case invoiceitem.FieldDescription:
			values[i] = new(sql.NullString)
		case invoiceitem.FieldOrderCreatedAt, invoiceitem.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceItem fields.
func (_m *InvoiceItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoiceitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoiceitem.FieldInvoiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_id", values[i])
			} else if value.Valid {
				_m.InvoiceID = value.Int64
			}
		case invoiceitem.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case invoiceitem.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case invoiceitem.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case invoiceitem.FieldOrderCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field order_created_at", values[i])
			} else if value.Valid {
				_m.OrderCreatedAt = new(time.Time)
				*_m.OrderCreatedAt = value.Time
			}
		case invoiceitem.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case invoiceitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceItem.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvoice queries the "invoice" edge of the InvoiceItem entity.
func (_m *InvoiceItem) QueryInvoice() *InvoiceQuery {
	return NewInvoiceItemClient(_m.config).QueryInvoice(_m)
}

// Update returns a builder for updating this InvoiceItem.
// Note that you need to call InvoiceItem.Unwrap() before calling this method if this InvoiceItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceItem) Update() *InvoiceItemUpdateOne {
	return NewInvoiceItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceItem) Unwrap() *InvoiceItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceItem) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invoice_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	if v := _m.OrderCreatedAt; v != nil {
		builder.WriteString("order_created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceItems is a parsable slice of InvoiceItem.
type InvoiceItems []*InvoiceItem
