// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/invoiceitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceItemUpdate is the builder for updating InvoiceItem entities.
type InvoiceItemUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// Where appends a list predicates to the InvoiceItemUpdate builder.
func (_u *InvoiceItemUpdate) Where(ps ...predicate.InvoiceItem) *InvoiceItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInvoiceID sets the "invoice_id" field.
func (_u *InvoiceItemUpdate) SetInvoiceID(v int64) *InvoiceItemUpdate {
	_u.mutation.SetInvoiceID(v)
	return _u
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (_u *InvoiceItemUpdate) SetNillableInvoiceID(v *int64) *InvoiceItemUpdate {
	if v != nil {
		_u.SetInvoiceID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *InvoiceItemUpdate) SetOrderID(v int64) *InvoiceItemUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *InvoiceItemUpdate) SetNillableOrderID(v *int64) *InvoiceItemUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *InvoiceItemUpdate) AddOrderID(v int64) *InvoiceItemUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *InvoiceItemUpdate) SetDescription(v string) *InvoiceItemUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InvoiceItemUpdate) SetNillableDescription(v *string) *InvoiceItemUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceItemUpdate) SetAmount(v float64) *InvoiceItemUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceItemUpdate) SetNillableAmount(v *float64) *InvoiceItemUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceItemUpdate) AddAmount(v float64) *InvoiceItemUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (_u *InvoiceItemUpdate) SetOrderCreatedAt(v time.Time) *InvoiceItemUpdate {
	_u.mutation.SetOrderCreatedAt(v)
	return _u
}

// SetNillableOrderCreatedAt sets the "order_created_at" field if the given value is not nil.
func (_u *InvoiceItemUpdate) SetNillableOrderCreatedAt(v *time.Time) *InvoiceItemUpdate {
	if v != nil {
		_u.SetOrderCreatedAt(*v)
	}
	return _u
}

// ClearOrderCreatedAt clears the value of the "order_created_at" field.
func (_u *InvoiceItemUpdate) ClearOrderCreatedAt() *InvoiceItemUpdate {
	_u.mutation.ClearOrderCreatedAt()
	return _u
}

// SetActive sets the "active" field.
func (_u *InvoiceItemUpdate) SetActive(v bool) *InvoiceItemUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *InvoiceItemUpdate) SetNillableActive(v *bool) *InvoiceItemUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetInvoice sets the "invoice" edge to the Invoice entity.
func (_u *InvoiceItemUpdate) SetInvoice(v *Invoice) *InvoiceItemUpdate {
	return _u.SetInvoiceID(v.ID)
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (_u *InvoiceItemUpdate) Mutation() *InvoiceItemMutation {
	return _u.mutation
}

// ClearInvoice clears the "invoice" edge to the Invoice entity.
func (_u *InvoiceItemUpdate) ClearInvoice() *InvoiceItemUpdate {
	_u.mutation.ClearInvoice()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceItemUpdate) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := invoiceitem.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.description": %w`, err)}
		}
	}
	if _u.mutation.InvoiceCleared() && len(_u.mutation.InvoiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceItem.invoice"`)
	}
	return nil
}

func (_u *InvoiceItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceitem.Table, invoiceitem.Columns, sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(invoiceitem.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(invoiceitem.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(invoiceitem.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoiceitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoiceitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OrderCreatedAt(); ok {
		_spec.SetField(invoiceitem.FieldOrderCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCreatedAtCleared() {
		_spec.ClearField(invoiceitem.FieldOrderCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(invoiceitem.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.InvoiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceItemUpdateOne is the builder for updating a single InvoiceItem entity.
type InvoiceItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// SetInvoiceID sets the "invoice_id" field.
func (_u *InvoiceItemUpdateOne) SetInvoiceID(v int64) *InvoiceItemUpdateOne {
	_u.mutation.SetInvoiceID(v)
	return _u
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (_u *InvoiceItemUpdateOne) SetNillableInvoiceID(v *int64) *InvoiceItemUpdateOne {
	if v != nil {
		_u.SetInvoiceID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *InvoiceItemUpdateOne) SetOrderID(v int64) *InvoiceItemUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *InvoiceItemUpdateOne) SetNillableOrderID(v *int64) *InvoiceItemUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *InvoiceItemUpdateOne) AddOrderID(v int64) *InvoiceItemUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *InvoiceItemUpdateOne) SetDescription(v string) *InvoiceItemUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InvoiceItemUpdateOne) SetNillableDescription(v *string) *InvoiceItemUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceItemUpdateOne) SetAmount(v float64) *InvoiceItemUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceItemUpdateOne) SetNillableAmount(v *float64) *InvoiceItemUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceItemUpdateOne) AddAmount(v float64) *InvoiceItemUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (_u *InvoiceItemUpdateOne) SetOrderCreatedAt(v time.Time) *InvoiceItemUpdateOne {
	_u.mutation.SetOrderCreatedAt(v)
	return _u
}

// SetNillableOrderCreatedAt sets the "order_created_at" field if the given value is not nil.
func (_u *InvoiceItemUpdateOne) SetNillableOrderCreatedAt(v *time.Time) *InvoiceItemUpdateOne {
	if v != nil {
		_u.SetOrderCreatedAt(*v)
	}
	return _u
}

// ClearOrderCreatedAt clears the value of the "order_created_at" field.
func (_u *InvoiceItemUpdateOne) ClearOrderCreatedAt() *InvoiceItemUpdateOne {
	_u.mutation.ClearOrderCreatedAt()
	return _u
}

// SetActive sets the "active" field.
func (_u *InvoiceItemUpdateOne) SetActive(v bool) *InvoiceItemUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *InvoiceItemUpdateOne) SetNillableActive(v *bool) *InvoiceItemUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetInvoice sets the "invoice" edge to the Invoice entity.
func (_u *InvoiceItemUpdateOne) SetInvoice(v *Invoice) *InvoiceItemUpdateOne {
	return _u.SetInvoiceID(v.ID)
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (_u *InvoiceItemUpdateOne) Mutation() *InvoiceItemMutation {
	return _u.mutation
}

// ClearInvoice clears the "invoice" edge to the Invoice entity.
func (_u *InvoiceItemUpdateOne) ClearInvoice() *InvoiceItemUpdateOne {
	_u.mutation.ClearInvoice()
	return _u
}

// Where appends a list predicates to the InvoiceItemUpdate builder.
func (_u *InvoiceItemUpdateOne) Where(ps ...predicate.InvoiceItem) *InvoiceItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceItemUpdateOne) Select(field string, fields ...string) *InvoiceItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceItem entity.
func (_u *InvoiceItemUpdateOne) Save(ctx context.Context) (*InvoiceItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceItemUpdateOne) SaveX(ctx context.Context) *InvoiceItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceItemUpdateOne) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := invoiceitem.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.description": %w`, err)}
		}
	}
	if _u.mutation.InvoiceCleared() && len(_u.mutation.InvoiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceItem.invoice"`)
	}
	return nil
}

func (_u *InvoiceItemUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceitem.Table, invoiceitem.Columns, sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceitem.FieldID)
		for _, f := range fields {
			if !invoiceitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(invoiceitem.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(invoiceitem.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(invoiceitem.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoiceitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoiceitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OrderCreatedAt(); ok {
		_spec.SetField(invoiceitem.FieldOrderCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCreatedAtCleared() {
		_spec.ClearField(invoiceitem.FieldOrderCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(invoiceitem.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.InvoiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
