// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/invoiceitem"
)

// InvoiceItemCreate is the builder for creating a InvoiceItem entity.
type InvoiceItemCreate struct {
	config
	mutation *InvoiceItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInvoiceID sets the "invoice_id" field.
func (_c *InvoiceItemCreate) SetInvoiceID(v int64) *InvoiceItemCreate {
	_c.mutation.SetInvoiceID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *InvoiceItemCreate) SetOrderID(v int64) *InvoiceItemCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *InvoiceItemCreate) SetDescription(v string) *InvoiceItemCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *InvoiceItemCreate) SetNillableDescription(v *string) *InvoiceItemCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceItemCreate) SetAmount(v float64) *InvoiceItemCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *InvoiceItemCreate) SetNillableAmount(v *float64) *InvoiceItemCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (_c *InvoiceItemCreate) SetOrderCreatedAt(v time.Time) *InvoiceItemCreate {
	_c.mutation.SetOrderCreatedAt(v)
	return _c
}

// SetNillableOrderCreatedAt sets the "order_created_at" field if the given value is not nil.
func (_c *InvoiceItemCreate) SetNillableOrderCreatedAt(v *time.Time) *InvoiceItemCreate {
	if v != nil {
		_c.SetOrderCreatedAt(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *InvoiceItemCreate) SetActive(v bool) *InvoiceItemCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *InvoiceItemCreate) SetNillableActive(v *bool) *InvoiceItemCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceItemCreate) SetCreatedAt(v time.Time) *InvoiceItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceItemCreate) SetNillableCreatedAt(v *time.Time) *InvoiceItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInvoice sets the "invoice" edge to the Invoice entity.
func (_c *InvoiceItemCreate) SetInvoice(v *Invoice) *InvoiceItemCreate {
	return _c.SetInvoiceID(v.ID)
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (_c *InvoiceItemCreate) Mutation() *InvoiceItemMutation {
	return _c.mutation
}

// Save creates the InvoiceItem in the database.
func (_c *InvoiceItemCreate) Save(ctx context.Context) (*InvoiceItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceItemCreate) SaveX(ctx context.Context) *InvoiceItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceItemCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := invoiceitem.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := invoiceitem.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := invoiceitem.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceItemCreate) check() error {
	if _, ok := _c.mutation.InvoiceID(); !ok {
		return &ValidationError{Name: "invoice_id", err: errors.New(`ent: missing required field "InvoiceItem.invoice_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "InvoiceItem.order_id"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "InvoiceItem.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := invoiceitem.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceItem.amount"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "InvoiceItem.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceItem.created_at"`)}
	}
	if len(_c.mutation.InvoiceIDs()) == 0 {
		return &ValidationError{Name: "invoice", err: errors.New(`ent: missing required edge "InvoiceItem.invoice"`)}
	}
	return nil
}

func (_c *InvoiceItemCreate) sqlSave(ctx context.Context) (*InvoiceItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceItemCreate) createSpec() (*InvoiceItem, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceitem.Table, sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(invoiceitem.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(invoiceitem.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoiceitem.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.OrderCreatedAt(); ok {
		_spec.SetField(invoiceitem.FieldOrderCreatedAt, field.TypeTime, value)
		_node.OrderCreatedAt = &value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(invoiceitem.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.InvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InvoiceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceItem.Create().
//		SetInvoiceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceItemUpsert) {
//			SetInvoiceID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceItemCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceItemUpsertOne {
	_c.conflict = opts
	return &InvoiceItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceItemCreate) OnConflictColumns(columns ...string) *InvoiceItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceItemUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceItemUpsertOne is the builder for "upsert"-ing
	//  one InvoiceItem node.
	InvoiceItemUpsertOne struct {
		create *InvoiceItemCreate
	}

	// InvoiceItemUpsert is the "OnConflict" setter.
	InvoiceItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetInvoiceID sets the "invoice_id" field.
func (u *InvoiceItemUpsert) SetInvoiceID(v int64) *InvoiceItemUpsert {
	u.Set(invoiceitem.FieldInvoiceID, v)
	return u
}

// UpdateInvoiceID sets the "invoice_id" field to the value that was provided on create.
func (u *InvoiceItemUpsert) UpdateInvoiceID() *InvoiceItemUpsert {
	u.SetExcluded(invoiceitem.FieldInvoiceID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *InvoiceItemUpsert) SetOrderID(v int64) *InvoiceItemUpsert {
	u.Set(invoiceitem.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *InvoiceItemUpsert) UpdateOrderID() *InvoiceItemUpsert {
	u.SetExcluded(invoiceitem.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *InvoiceItemUpsert) AddOrderID(v int64) *InvoiceItemUpsert {
	u.Add(invoiceitem.FieldOrderID, v)
	return u
}

// SetDescription sets the "description" field.
func (u *InvoiceItemUpsert) SetDescription(v string) *InvoiceItemUpsert {
	u.Set(invoiceitem.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *InvoiceItemUpsert) UpdateDescription() *InvoiceItemUpsert {
	u.SetExcluded(invoiceitem.FieldDescription)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceItemUpsert) SetAmount(v float64) *InvoiceItemUpsert {
	u.Set(invoiceitem.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceItemUpsert) UpdateAmount() *InvoiceItemUpsert {
	u.SetExcluded(invoiceitem.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceItemUpsert) AddAmount(v float64) *InvoiceItemUpsert {
	u.Add(invoiceitem.FieldAmount, v)
	return u
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (u *InvoiceItemUpsert) SetOrderCreatedAt(v time.Time) *InvoiceItemUpsert {
	u.Set(invoiceitem.FieldOrderCreatedAt, v)
	return u
}

// UpdateOrderCreatedAt sets the "order_created_at" field to the value that was provided on create.
func (u *InvoiceItemUpsert) UpdateOrderCreatedAt() *InvoiceItemUpsert {
	u.SetExcluded(invoiceitem.FieldOrderCreatedAt)
	return u
}

// ClearOrderCreatedAt clears the value of the "order_created_at" field.
func (u *InvoiceItemUpsert) ClearOrderCreatedAt() *InvoiceItemUpsert {
	u.SetNull(invoiceitem.FieldOrderCreatedAt)
	return u
}

// SetActive sets the "active" field.
func (u *InvoiceItemUpsert) SetActive(v bool) *InvoiceItemUpsert {
	u.Set(invoiceitem.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *InvoiceItemUpsert) UpdateActive() *InvoiceItemUpsert {
	u.SetExcluded(invoiceitem.FieldActive)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceItemUpsertOne) UpdateNewValues() *InvoiceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceItemUpsertOne) Ignore() *InvoiceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceItemUpsertOne) DoNothing() *InvoiceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceItemCreate.OnConflict
// documentation for more info.
func (u *InvoiceItemUpsertOne) Update(set func(*InvoiceItemUpsert)) *InvoiceItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceID sets the "invoice_id" field.
func (u *InvoiceItemUpsertOne) SetInvoiceID(v int64) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetInvoiceID(v)
	})
}

// UpdateInvoiceID sets the "invoice_id" field to the value that was provided on create.
func (u *InvoiceItemUpsertOne) UpdateInvoiceID() *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateInvoiceID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *InvoiceItemUpsertOne) SetOrderID(v int64) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *InvoiceItemUpsertOne) AddOrderID(v int64) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *InvoiceItemUpsertOne) UpdateOrderID() *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateOrderID()
	})
}

// SetDescription sets the "description" field.
func (u *InvoiceItemUpsertOne) SetDescription(v string) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *InvoiceItemUpsertOne) UpdateDescription() *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateDescription()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceItemUpsertOne) SetAmount(v float64) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceItemUpsertOne) AddAmount(v float64) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceItemUpsertOne) UpdateAmount() *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateAmount()
	})
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (u *InvoiceItemUpsertOne) SetOrderCreatedAt(v time.Time) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetOrderCreatedAt(v)
	})
}

// UpdateOrderCreatedAt sets the "order_created_at" field to the value that was provided on create.
func (u *InvoiceItemUpsertOne) UpdateOrderCreatedAt() *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateOrderCreatedAt()
	})
}

// ClearOrderCreatedAt clears the value of the "order_created_at" field.
func (u *InvoiceItemUpsertOne) ClearOrderCreatedAt() *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.ClearOrderCreatedAt()
	})
}

// SetActive sets the "active" field.
func (u *InvoiceItemUpsertOne) SetActive(v bool) *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *InvoiceItemUpsertOne) UpdateActive() *InvoiceItemUpsertOne {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateActive()
	})
}

// Exec executes the query.
func (u *InvoiceItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceItemCreateBulk is the builder for creating many InvoiceItem entities in bulk.
type InvoiceItemCreateBulk struct {
	config
	err      error
	builders []*InvoiceItemCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceItem entities in the database.
func (_c *InvoiceItemCreateBulk) Save(ctx context.Context) ([]*InvoiceItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceItemCreateBulk) SaveX(ctx context.Context) []*InvoiceItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceItemUpsert) {
//			SetInvoiceID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceItemUpsertBulk {
	_c.conflict = opts
	return &InvoiceItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceItemCreateBulk) OnConflictColumns(columns ...string) *InvoiceItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceItemUpsertBulk{
		create: _c,
	}
}

// InvoiceItemUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceItem nodes.
type InvoiceItemUpsertBulk struct {
	create *InvoiceItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceItemUpsertBulk) UpdateNewValues() *InvoiceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceItemUpsertBulk) Ignore() *InvoiceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceItemUpsertBulk) DoNothing() *InvoiceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceItemCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceItemUpsertBulk) Update(set func(*InvoiceItemUpsert)) *InvoiceItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceID sets the "invoice_id" field.
func (u *InvoiceItemUpsertBulk) SetInvoiceID(v int64) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetInvoiceID(v)
	})
}

// UpdateInvoiceID sets the "invoice_id" field to the value that was provided on create.
func (u *InvoiceItemUpsertBulk) UpdateInvoiceID() *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateInvoiceID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *InvoiceItemUpsertBulk) SetOrderID(v int64) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *InvoiceItemUpsertBulk) AddOrderID(v int64) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *InvoiceItemUpsertBulk) UpdateOrderID() *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateOrderID()
	})
}

// SetDescription sets the "description" field.
func (u *InvoiceItemUpsertBulk) SetDescription(v string) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *InvoiceItemUpsertBulk) UpdateDescription() *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateDescription()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceItemUpsertBulk) SetAmount(v float64) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceItemUpsertBulk) AddAmount(v float64) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceItemUpsertBulk) UpdateAmount() *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateAmount()
	})
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (u *InvoiceItemUpsertBulk) SetOrderCreatedAt(v time.Time) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetOrderCreatedAt(v)
	})
}

// UpdateOrderCreatedAt sets the "order_created_at" field to the value that was provided on create.
func (u *InvoiceItemUpsertBulk) UpdateOrderCreatedAt() *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateOrderCreatedAt()
	})
}

// ClearOrderCreatedAt clears the value of the "order_created_at" field.
func (u *InvoiceItemUpsertBulk) ClearOrderCreatedAt() *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.ClearOrderCreatedAt()
	})
}

// SetActive sets the "active" field.
func (u *InvoiceItemUpsertBulk) SetActive(v bool) *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *InvoiceItemUpsertBulk) UpdateActive() *InvoiceItemUpsertBulk {
	return u.Update(func(s *InvoiceItemUpsert) {
		s.UpdateActive()
	})
}

// Exec executes the query.
func (u *InvoiceItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
