// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
)

// Invoice is the model entity for the Invoice schema.
type Invoice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// InvoiceNo holds the value of the "invoice_no" field.
	InvoiceNo string `json:"invoice_no,omitempty"`
	// EntityType holds the value of the "entity_type" field.
	EntityType string `json:"entity_type,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// TaxID holds the value of the "tax_id" field.
	TaxID *string `json:"tax_id,omitempty"`
	// DeliveryEmail holds the value of the "delivery_email" field.
	DeliveryEmail string `json:"delivery_email,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IssuedInvoiceNo holds the value of the "issued_invoice_no" field.
	IssuedInvoiceNo *string `json:"issued_invoice_no,omitempty"`
	// IssuedFileURL holds the value of the "issued_file_url" field.
	IssuedFileURL *string `json:"issued_file_url,omitempty"`
	// RejectReason holds the value of the "reject_reason" field.
	RejectReason *string `json:"reject_reason,omitempty"`
	// ReviewedBy holds the value of the "reviewed_by" field.
	ReviewedBy *int64 `json:"reviewed_by,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceQuery when eager-loading is set.
	Edges        InvoiceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceEdges holds the relations/edges for other nodes in the graph.
type InvoiceEdges struct {
	// Items holds the value of the items edge.
	Items []*InvoiceItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) ItemsOrErr() ([]*InvoiceItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invoice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoice.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case invoice.FieldID, invoice.FieldUserID, invoice.FieldReviewedBy:
			values[i] = new(sql.NullInt64)
		case invoice.FieldInvoiceNo, invoice.FieldEntityType, invoice.FieldTitle, invoice.FieldTaxID, invoice.FieldDeliveryEmail, invoice.FieldNotes, invoice.FieldStatus, invoice.FieldIssuedInvoiceNo, invoice.FieldIssuedFileURL, invoice.FieldRejectReason:
			values[i] = new(sql.NullString)
		case invoice.FieldReviewedAt, invoice.FieldCreatedAt, invoice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invoice fields.
func (_m *Invoice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoice.FieldInvoiceNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_no", values[i])
			} else if value.Valid {
				_m.InvoiceNo = value.String
			}
		case invoice.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				_m.EntityType = value.String
			}
		case invoice.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case invoice.FieldTaxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_id", values[i])
			} else if value.Valid {
				_m.TaxID = new(string)
				*_m.TaxID = value.String
			}
		case invoice.FieldDeliveryEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_email", values[i])
			} else if value.Valid {
				_m.DeliveryEmail = value.String
			}
		case invoice.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case invoice.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case invoice.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoice.FieldIssuedInvoiceNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issued_invoice_no", values[i])
			} else if value.Valid {
				_m.IssuedInvoiceNo = new(string)
				*_m.IssuedInvoiceNo = value.String
			}
		case invoice.FieldIssuedFileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issued_file_url", values[i])
			} else if value.Valid {
				_m.IssuedFileURL = new(string)
				*_m.IssuedFileURL = value.String
			}
		case invoice.FieldRejectReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reject_reason", values[i])
			} else if value.Valid {
				_m.RejectReason = new(string)
				*_m.RejectReason = value.String
			}
		case invoice.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = new(int64)
				*_m.ReviewedBy = value.Int64
			}
		case invoice.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case invoice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invoice.
// This includes values selected through modifiers, order, etc.
func (_m *Invoice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the Invoice entity.
func (_m *Invoice) QueryItems() *InvoiceItemQuery {
	return NewInvoiceClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this Invoice.
// Note that you need to call Invoice.Unwrap() before calling this method if this Invoice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Invoice) Update() *InvoiceUpdateOne {
	return NewInvoiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Invoice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Invoice) Unwrap() *Invoice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Invoice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Invoice) String() string {
	var builder strings.Builder
	builder.WriteString("Invoice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("invoice_no=")
	builder.WriteString(_m.InvoiceNo)
	builder.WriteString(", ")
	builder.WriteString("entity_type=")
	builder.WriteString(_m.EntityType)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.TaxID; v != nil {
		builder.WriteString("tax_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("delivery_email=")
	builder.WriteString(_m.DeliveryEmail)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.IssuedInvoiceNo; v != nil {
		builder.WriteString("issued_invoice_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IssuedFileURL; v != nil {
		builder.WriteString("issued_file_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RejectReason; v != nil {
		builder.WriteString("reject_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReviewedBy; v != nil {
		builder.WriteString("reviewed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Invoices is a parsable slice of Invoice.
type Invoices []*Invoice
