// Code generated by ent, DO NOT EDIT.

package invoiceitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldID, id))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldInvoiceID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldDescription, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldAmount, v))
}

// OrderCreatedAt applies equality check predicate on the "order_created_at" field. It's identical to OrderCreatedAtEQ.
func OrderCreatedAt(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderCreatedAt, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldCreatedAt, v))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldOrderID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContainsFold(FieldDescription, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldAmount, v))
}

// OrderCreatedAtEQ applies the EQ predicate on the "order_created_at" field.
func OrderCreatedAtEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderCreatedAt, v))
}

// OrderCreatedAtNEQ applies the NEQ predicate on the "order_created_at" field.
func OrderCreatedAtNEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldOrderCreatedAt, v))
}

// OrderCreatedAtIn applies the In predicate on the "order_created_at" field.
func OrderCreatedAtIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldOrderCreatedAt, vs...))
}

// OrderCreatedAtNotIn applies the NotIn predicate on the "order_created_at" field.
func OrderCreatedAtNotIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldOrderCreatedAt, vs...))
}

// OrderCreatedAtGT applies the GT predicate on the "order_created_at" field.
func OrderCreatedAtGT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldOrderCreatedAt, v))
}

// OrderCreatedAtGTE applies the GTE predicate on the "order_created_at" field.
func OrderCreatedAtGTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldOrderCreatedAt, v))
}

// OrderCreatedAtLT applies the LT predicate on the "order_created_at" field.
func OrderCreatedAtLT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldOrderCreatedAt, v))
}

// OrderCreatedAtLTE applies the LTE predicate on the "order_created_at" field.
func OrderCreatedAtLTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldOrderCreatedAt, v))
}

// OrderCreatedAtIsNil applies the IsNil predicate on the "order_created_at" field.
func OrderCreatedAtIsNil() predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIsNull(FieldOrderCreatedAt))
}

// OrderCreatedAtNotNil applies the NotNil predicate on the "order_created_at" field.
func OrderCreatedAtNotNil() predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotNull(FieldOrderCreatedAt))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldCreatedAt, v))
}

// HasInvoice applies the HasEdge predicate on the "invoice" edge.
func HasInvoice() predicate.InvoiceItem {
	return predicate.InvoiceItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceTable, InvoiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceWith applies the HasEdge predicate on the "invoice" edge with a given conditions (other predicates).
func HasInvoiceWith(preds ...predicate.Invoice) predicate.InvoiceItem {
	return predicate.InvoiceItem(func(s *sql.Selector) {
		step := newInvoiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceItem) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceItem) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceItem) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.NotPredicates(p))
}
